// Generated by scripts/generate-public-ipc.mjs. Edit ipc/publicContract.ts instead.
import { contextBridge, ipcRenderer } from 'electron';
import type { NativeWindowThemeMode, NativeWindowThemeResult } from '../ipc/publicTypes.js';
import type {
  AiAgentApprovalResponseRequest,
  AiAgentCancelIpcResult,
  AiAgentEventEnvelope,
  AiAgentEventReplayIpcResult,
  AiAgentPermissionRequestResult,
  AiAgentRunIpcResult,
  AiAgentRunRequest,
  AiAgentSessionListIpcResult,
  AiAgentSessionLoadIpcResult,
  AgentAttachmentCreateIpcResult,
  AgentResourceReferenceCreateIpcResult,
  AnalyzeWorkspaceSummary,
  DirectorySelection,
  OpenWorkspaceScanOptions,
  RendererWorkspaceScanResult,
  RendererWorkspaceSession,
  RollbackOperationIpcResult,
  TextCatalogResponse
} from '../ipc/publicTypes.js';
import type {
  RendererIndexedFile,
  RendererPatchHistoryEntry,
  RendererResourcePreview,
  RendererSaveResult
} from '../ipc/publicTypes.js';
import type {
  AiSidebarDraft,
  AiSidebarDraftRequest,
  EmedfCompletionItem,
  ResourceCapabilityMatrix,
  ToolDescriptor,
  ToolResult,
  ModelThinkingLevel,
  MemoryEntry
} from '@soulforge/core';
import type {
  AgentResourceReference,
  ApplyEditorMutationRequest,
  ApplyEditorMutationValue,
  Diagnostic,
  EditorContentValue,
  EditorDocumentPageValue,
  EditorDocumentResult,
  EditorPageQuery,
  EditorSelectionContext,
  FeedbackStatusIpcResult,
  FmgEntryPage,
  MutterNextIpcResult,
  MutterStatusIpcResult,
  OpenEditorDocumentRequest,
  OpenEditorDocumentValue,
  PageEditorDocumentRequest,
  ParamFieldDef,
  ParamRowPage,
  RagRetrieveResult,
  ReadEditorContentRequest,
  RendererContainerChildBytes,
  RendererContainerChildrenList,
  RendererContainerChildrenPage,
  RendererContainerTreeSummary,
  ScriptContainerEntryPage,
  ScriptContainerEvidence,
  ScriptEntryPlaintextView,
  SessionFeedbackIpcRequest,
  SessionFeedbackIpcResult,
  SubmitAllHistoryIpcResult,
  CiteHit,
  MapEditTransaction,
  UpdateCommandResult,
  UpdateSetChannelRequest,
  UpdateStateEvent,
  UpdatePublicState
} from '@soulforge/shared';
import { AUXILIARY_IPC_CHANNELS, EDITOR_DOCUMENT_IPC_CHANNELS, PARAM_SESSION_IPC_CHANNELS, UPDATE_IPC_CHANNELS } from '@soulforge/shared';
import type {
  OpenParamSessionRequest,
  OpenParamSessionResult,
  ReadParamIndexPageRequest,
  ParamIndexPageResult,
  ReadParamRowsRequest,
  ParamRowPayloadBatchResult
} from '@soulforge/shared';
import type { MapReadCancellationResult } from '../ipc/publicTypes.js';
import type { SoulForgeApi } from '../ipc/publicApi.generated.js';
import { stripPathFields } from './resultTransforms.js';

const api: SoulForgeApi = {
  setWindowThemeMode: (mode: NativeWindowThemeMode): Promise<NativeWindowThemeResult> =>
    ipcRenderer.invoke('window.setThemeMode', mode),
  openEditorDocument: (request: OpenEditorDocumentRequest): Promise<EditorDocumentResult<OpenEditorDocumentValue>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.open, request),
  getEditorDocument: (documentHandle: string): Promise<EditorDocumentResult<OpenEditorDocumentValue>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.get, documentHandle),
  pageEditorDocument: (request: PageEditorDocumentRequest): Promise<EditorDocumentResult<EditorDocumentPageValue>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.page, request),
  readEditorDocumentContent: (request: ReadEditorContentRequest): Promise<EditorDocumentResult<EditorContentValue>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.readContent, request),
  applyEditorMutation: (request: ApplyEditorMutationRequest): Promise<EditorDocumentResult<ApplyEditorMutationValue>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.apply, request),
  closeEditorDocument: (documentHandle: string): Promise<EditorDocumentResult<{ closed: true }>> =>
    ipcRenderer.invoke(EDITOR_DOCUMENT_IPC_CHANNELS.close, documentHandle),
  lastWorkspaceSelection: (): Promise<{
    overlay: DirectorySelection | null;
    base: DirectorySelection | null;
  }> =>
    ipcRenderer.invoke('workspace.lastSelection'),
  openWorkspaceDialog: (): Promise<DirectorySelection | null> =>
    ipcRenderer.invoke('workspace.openDialog'),
  openBaseDialog: (): Promise<DirectorySelection | null> =>
    ipcRenderer.invoke('workspace.openBaseDialog'),
  scanWorkspace: (options: OpenWorkspaceScanOptions): Promise<RendererWorkspaceScanResult> =>
    ipcRenderer.invoke('workspace.scan', options),
  remountBase: (baseSelectionId: string | null): Promise<{
    workspaceSessionId: string;
    session: RendererWorkspaceSession;
  }> =>
    ipcRenderer.invoke('workspace.remountBase', baseSelectionId),
  detectMe3: (): Promise<import('@soulforge/core').RuntimeCapability> =>
    ipcRenderer.invoke('runtime.detectMe3'),
  prepareMe3Profile: (): Promise<import('@soulforge/core').RuntimeOperationResult<import('@soulforge/core').RuntimeProfileRef>> =>
    ipcRenderer.invoke('runtime.prepareMe3Profile'),
  launchMe3: (profileId: string): Promise<import('@soulforge/core').RuntimeOperationResult<import('@soulforge/core').RuntimeLaunchSession>> =>
    ipcRenderer.invoke('runtime.launchMe3', profileId),
  terminateMe3: (sessionId: string): Promise<import('@soulforge/core').RuntimeOperationResult<import('@soulforge/core').RuntimeTerminationResult>> =>
    ipcRenderer.invoke('runtime.terminateMe3', sessionId),
  analyzeWorkspace: (): Promise<AnalyzeWorkspaceSummary> =>
    ipcRenderer.invoke('workspace.analyze'),
  searchResources: (query: string): Promise<RendererIndexedFile[]> =>
    ipcRenderer.invoke('resource.search', query),
  openResourcePreview: (sourceUri: string): Promise<RendererResourcePreview | null> =>
    ipcRenderer.invoke('resource.preview', sourceUri),
  saveTextResource: (sourceUri: string, newText: string): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.saveText', sourceUri, newText),
  readRawMetadata: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readRawMetadata', sourceUri),
  readRawRange: (sourceUri: string, offset: number, length: number): Promise<unknown> =>
    ipcRenderer.invoke('resource.readRawRange', sourceUri, offset, length),
  inspectContainerTree: (sourceUri: string): Promise<RendererContainerTreeSummary> =>
    ipcRenderer.invoke('resource.inspectContainerTree', sourceUri).then(stripPathFields),
  listContainerChildren: (sourceUri: string, recursive?: boolean): Promise<RendererContainerChildrenList> =>
    ipcRenderer.invoke('resource.listContainerChildren', sourceUri, recursive),
  listContainerChildrenPage: (sourceUri: string, page: number, pageSize: number, recursive?: boolean): Promise<RendererContainerChildrenPage> =>
    ipcRenderer.invoke('resource.listContainerChildrenPage', sourceUri, page, pageSize, recursive).then(stripPathFields),
  readContainerChild: (childUri: string): Promise<RendererContainerChildBytes> =>
    ipcRenderer.invoke('resource.readContainerChild', childUri),
  replaceContainerChild: (childUri: string, expectedContainerHash: string, expectedChildHash: string, newContentBase64: string): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.replaceContainerChild', childUri, expectedContainerHash, expectedChildHash, newContentBase64),
  roundTripContainer: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.roundTripContainer', sourceUri),
  validateContainer: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.validateContainer', sourceUri),
  probeContainerCapabilities: (sourceUri: string): Promise<ResourceCapabilityMatrix | null> =>
    ipcRenderer.invoke('resource.probeContainerCapabilities', sourceUri),
  scriptContainerEvidence: (sourceUri: string): Promise<ScriptContainerEvidence> =>
    ipcRenderer.invoke('resource.scriptContainerEvidence', sourceUri).then(stripPathFields),
  listScriptContainerEntriesPage: (sourceUri: string, page: number, pageSize: number): Promise<ScriptContainerEntryPage> =>
    ipcRenderer.invoke('resource.listScriptContainerEntriesPage', sourceUri, page, pageSize).then(stripPathFields),
  readScriptEntryPlaintext: (sourceUri: string, entryName: string): Promise<ScriptEntryPlaintextView> =>
    ipcRenderer.invoke('resource.readScriptEntryPlaintext', sourceUri, entryName),
  readScriptSource: (sourceUri: string, entryName?: string, entryIndex?: number): Promise<import('@soulforge/shared').ScriptSourceView> =>
    ipcRenderer.invoke('resource.readScriptSource', sourceUri, entryName, entryIndex),
  saveScriptSource: (sourceUri: string, entryName: string | undefined, expectedChildHash: string | undefined, expectedContainerHash: string | undefined, sourceText: string, encoding?: string, entryIndex?: number): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.saveScriptSource', sourceUri, entryName, expectedChildHash, expectedContainerHash, sourceText, encoding, entryIndex),
  listOperations: (): Promise<RendererPatchHistoryEntry[]> =>
    ipcRenderer.invoke('operation.list'),
  rollbackOperation: (opId: string): Promise<RollbackOperationIpcResult> =>
    ipcRenderer.invoke('operation.rollback', opId),
  rollbackFile: (opId: string, targetUri: string): Promise<RollbackOperationIpcResult> =>
    ipcRenderer.invoke('operation.rollbackFile', opId, targetUri),
  readEmevdDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readEmevdDocument', sourceUri),
  applyEmevdMutation: (sourceUri: string, expectedHash: string, mutation: Record<string, unknown>): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyEmevdMutation', sourceUri, expectedHash, mutation),
  readEmevdFullDocument: (sourceUri: string, documentInstanceId: string, loadFullDslTemplate?: boolean): Promise<{
    ok?: boolean;
    /**
     * main 侧取消：本次打开已被更晚的打开请求取代（快速切换事件文件）。它与
     * `ok: false` 的读取失败必须分开处理 —— 取消不代表文件有问题，调用方要静默
     * 丢弃，不能渲染成「读不出来」。
     */
    cancelled?: boolean;
    documentInstanceId?: string;
    revision?: number;
    eventCount?: number;
    instructionCount?: number;
    /** R3/P4 裁定：DarkScript3 式源码；3.1 起首包不再带全文，全文走 sourceToken。 */
    dslTemplate?: string | null;
    /** 前 400 行，供首屏看见 $Event；其余走 readEmevdSourceSlice。 */
    sourcePrefix?: string | null;
    /** 只活在 main 的 opaque 令牌，不是路径。 */
    sourceToken?: string | null;
    sourceTotalLines?: number;
    /**
     * 源码形态：'dark-script'（EMEDF 反汇编，只读展示）、'patch-dsl'（旧 hash
     * DSL，仅历史路径）、'none'（EMEDF 缺失失败关闭）。
     */
    sourceStyle?: 'dark-script' | 'patch-dsl' | 'none';
    dslTemplateTruncated?: boolean;
    dslTemplateTotalLines?: number;
    sourceHash?: string | null;
    sourceFormat?: string | null;
    outerFileHash?: string | null;
    registryOrigin?: 'first-party' | 'imported' | 'fixture';
    registryPackageId?: string | null;
    registryPackageVersion?: string | null;
    registryContentDigest?: string | null;
    /** Bridge 往返判定：'native-verified'（语义+字节一致）/ 'candidate'（仅语义）。 */
    authority?: string | null;
    outline?: {
      schemaVersion: 1;
      resourceUri: string;
      eventCount: number;
      instructionTotal: number;
      truncated: boolean;
      limit: number;
      events: Array<{
        eventUri: string;
        eventId: number;
        restBehavior: number;
        layer: number;
        instructionCount: number;
        unknownCount: number;
      }>;
    } | null;
    diagnostics?: Array<{ severity: string; code: string; message: string }>;
  }> =>
    ipcRenderer.invoke('resource.readEmevdFullDocument', sourceUri, documentInstanceId, loadFullDslTemplate === true ? true : undefined),
  cancelEmevdFullDocument: (): Promise<{ ok: boolean; cancelled: boolean }> =>
    ipcRenderer.invoke('resource.cancelEmevdFullDocument'),
  readEmevdSourceSlice: (token: string, fromLine: number, lineCount: number): Promise<{
    ok?: boolean;
    cancelled?: boolean;
    code?: string;
    message?: string;
    fromLine?: number;
    lineCount?: number;
    totalLines?: number;
    eof?: boolean;
    sliceText?: string;
  }> =>
    ipcRenderer.invoke('resource.readEmevdSourceSlice', token, fromLine, lineCount),
  submitEmevdDslPlan: (sourceUri: string, sourceText: string, mode: 'patch' | 'dark-script' = 'patch'): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.submitEmevdDslPlan', sourceUri, sourceText, mode),
  readEmedfCompletionCatalog: (): Promise<{
    ok: boolean;
    origin: 'first-party' | 'imported' | 'fixture';
    items: EmedfCompletionItem[];
    enums?: Record<string, import('@soulforge/core').EmedfEnumDef>;
  }> =>
    ipcRenderer.invoke('resource.readEmedfCompletionCatalog'),
  readFmgDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFmgDocument', sourceUri),
  readFmgPage: (sourceUri: string, page: number, pageSize: number, query?: string): Promise<FmgEntryPage> =>
    ipcRenderer.invoke('resource.readFmgPage', sourceUri, page, pageSize, query),
  readTextCatalog: (): Promise<TextCatalogResponse> =>
    ipcRenderer.invoke('resource.readTextCatalog'),
  readFmgTablePage: (tableId: string, page: number, pageSize: number, query?: string): Promise<FmgEntryPage> =>
    ipcRenderer.invoke('resource.readFmgTablePage', tableId, page, pageSize, query),
  applyFmgMutation: (sourceUri: string, expectedHash: string, mutation: { kind: 'upsert' | 'delete' | 'add'; id: number; text?: string }, tableId?: string): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyFmgMutation', sourceUri, expectedHash, mutation, tableId),
  readMsbDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readMsbDocument', sourceUri),
  readTaeDocument: (sourceUri: string, options?: { animationPage?: number; animationPageSize?: number }): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTaeDocument', sourceUri, options),
  readTaeTemplateCatalog: (): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTaeTemplateCatalog'),
  readTaeEventParams: (sourceUri: string, animId: number, eventIndex: number, taeEntryIndex?: number, taeEntryId?: number, taeEntryName?: string, taeGroup?: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTaeEventParams', sourceUri, animId, eventIndex, taeEntryIndex, taeEntryId, taeEntryName, taeGroup),
  readTaeChrbndPreview: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTaeChrbndPreview', sourceUri),
  readTaeAnimationClip: (sourceUri: string, animId: number, flverBoneNames?: string[], flverBoneParents?: number[], flverReferencePose?: Array<{
      translation: [number, number, number];
      rotation: [number, number, number, number];
      scale: [number, number, number];
    }>, taeEntryIndex?: number, taeEntryId?: number, taeEntryName?: string, taeGroup?: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTaeAnimationClip', sourceUri, animId, flverBoneNames, flverBoneParents, flverReferencePose, taeEntryIndex, taeEntryId, taeEntryName, taeGroup),
  sampleTaeAnimationPose: (sourceUri: string, animId: number, timeSeconds: number, flverBoneNames?: string[], loop?: boolean, flverBoneParents?: number[], flverReferencePose?: Array<{
      translation: [number, number, number];
      rotation: [number, number, number, number];
      scale: [number, number, number];
    }>, taeEntryIndex?: number, taeEntryId?: number, taeEntryName?: string, taeGroup?: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.sampleTaeAnimationPose', sourceUri, animId, timeSeconds, flverBoneNames, loop, flverBoneParents, flverReferencePose, taeEntryIndex, taeEntryId, taeEntryName, taeGroup),
  readMapPartMesh: (msbSourceUri: string, modelName: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readMapPartMesh', msbSourceUri, modelName),
  readMapStaticGeometry: (msbSourceUri: string, modelName: string, cursor?: string | null, sessionToken?: string | null, requestId?: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readMapStaticGeometry', msbSourceUri, modelName, cursor ?? null, sessionToken ?? null, requestId ?? null),
  cancelMapStaticGeometry: (requestId: string): Promise<MapReadCancellationResult> =>
    ipcRenderer.invoke('resource.cancelMapStaticGeometry', requestId),
  readEsdDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readEsdDocument', sourceUri),
  readMtdDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readMtdDocument', sourceUri),
  readFxrDocument: (sourceUri: string, entryName?: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFxrDocument', sourceUri, entryName),
  listFxrEntries: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.listFxrEntries', sourceUri),
  readFlverDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFlverDocument', sourceUri),
  readTpfDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTpfDocument', sourceUri),
  readTpfTexturePreview: (sourceUri: string, textureIndex: number): Promise<unknown> =>
    ipcRenderer.invoke('resource.readTpfTexturePreview', sourceUri, textureIndex),
  saveTpfTextureReplace: (sourceUri: string, expectedHash: string, textureIndex: number, newTextureBase64: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.saveTpfTextureReplace', sourceUri, expectedHash, textureIndex, newTextureBase64),
  readFlverMesh: (sourceUri: string, meshIndex: number): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFlverMesh', sourceUri, meshIndex),
  readFlverSkeleton: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFlverSkeleton', sourceUri),
  readFlverDummies: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFlverDummies', sourceUri),
  readFlverTextureSlots: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readFlverTextureSlots', sourceUri),
  resolveChrbndPreview: (animSourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.resolveChrbndPreview', animSourceUri),
  applyMsbMutation: (sourceUri: string, expectedHash: string, mutation: {
      kind: 'set_part_position' | 'set_part_transform' | 'set_region_position'
        | 'delete_part' | 'delete_region' | 'delete_event';
      family: 'part' | 'region' | 'event';
      nativeOffset: number;
      expectedName?: string;
      posX?: number;
      posY?: number;
      posZ?: number;
      rotX?: number;
      scaleX?: number;
      scaleY?: number;
      scaleZ?: number;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyMsbMutation', sourceUri, expectedHash, mutation),
  executeMapTransaction: (sourceUri: string, expectedHash: string, transaction: MapEditTransaction): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.executeMapTransaction', sourceUri, expectedHash, transaction),
  applyFlverMutation: (sourceUri: string, expectedHash: string, mutation: {
      kind: 'material-slot-set';
      meshStableId: string;
      slotIndex: number;
      materialStableId: string;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyFlverMutation', sourceUri, expectedHash, mutation),
  readParamDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readParamDocument', sourceUri),
  readGparamDocument: (sourceUri: string): Promise<unknown> =>
    ipcRenderer.invoke('resource.readGparamDocument', sourceUri),
  commitGparamMutations: (sourceUri: string, expectedDocumentHash: string, mutations: Array<{
      groupId: number;
      paramId: number;
      valueIndex: number;
      value: number;
    }>): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.commitGparamMutations', sourceUri, expectedDocumentHash, mutations),
  commitMtdPropertySet: (sourceUri: string, expectedDocumentHash: string, set: { paramId: string; newValue: string }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.commitMtdPropertySet', sourceUri, expectedDocumentHash, set),
  commitEsdTransition: (sourceUri: string, expectedDocumentHash: string, mutations: Array<{
      mutation: string;
      stateRelOffset?: number;
      conditionRelOffset?: number;
      targetStateRelOffset?: number;
    }>): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.commitEsdTransition', sourceUri, expectedDocumentHash, mutations),
  commitTaeEvent: (sourceUri: string, expectedDocumentHash: string, mutations: Array<{
      mutation: string;
      animId?: number;
      eventIndex?: number;
      templateEventIndex?: number;
      eventTypeId?: number;
      startTime?: number;
      endTime?: number;
      fieldIndex?: number;
      fieldName?: string;
      value?: string | number | boolean;
      schemaBankId?: number;
      taeEntryIndex?: number;
    }>): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.commitTaeEvent', sourceUri, expectedDocumentHash, mutations),
  commitFxrFieldSet: (sourceUri: string, expectedDocumentHash: string, mutations: Array<{
      mutation: string;
      address: {
        container: string;
        hostIndex: number;
        propertyIndex?: number;
        section8Index?: number;
        valueIndex: number;
      };
      value: number;
    }>): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.commitFxrFieldSet', sourceUri, expectedDocumentHash, mutations),
  getParamMetadataTrustState: (): Promise<{
    ok: boolean;
    trusted: boolean;
    packageId: string | null;
    packageVersion: string | null;
    sourceIdentity?: string | null;
    sourceRevision?: string | null;
    licenseSpdxExpression?: string | null;
    confirmedAt?: string;
    diagnostics: Diagnostic[];
  }> =>
    ipcRenderer.invoke('param.metadata.trustState'),
  setParamMetadataTrust: (trusted: boolean): Promise<{
    ok: boolean;
    trusted?: boolean;
    diagnostics: Diagnostic[];
  }> =>
    ipcRenderer.invoke('param.metadata.setTrust', trusted),
  readParamPage: (sourceUri: string, page: number, pageSize: number, query?: string, loadAll?: boolean): Promise<ParamRowPage> =>
    ipcRenderer.invoke('resource.readParamPage', sourceUri, page, pageSize, query, loadAll),
  openParamSession: (request: OpenParamSessionRequest): Promise<OpenParamSessionResult> =>
    ipcRenderer.invoke(PARAM_SESSION_IPC_CHANNELS.open, request),
  readParamIndexPage: (request: ReadParamIndexPageRequest): Promise<ParamIndexPageResult> =>
    ipcRenderer.invoke(PARAM_SESSION_IPC_CHANNELS.readIndexPage, request),
  readParamRows: (request: ReadParamRowsRequest): Promise<ParamRowPayloadBatchResult> =>
    ipcRenderer.invoke(PARAM_SESSION_IPC_CHANNELS.readRows, request),
  listContainerParams: (containerUri: string): Promise<{
    ok: boolean;
    containerUri: string;
    containerFormat?: string | null;
    params: Array<{ entryIndex: number; name: string; size: number }>;
    diagnostics: Diagnostic[];
  }> =>
    ipcRenderer.invoke('resource.listContainerParams', containerUri),
  readContainerParamPage: (containerUri: string, entryIndex: number, page: number, pageSize: number, query?: string, loadAll?: boolean, documentSessionToken?: string): Promise<ParamRowPage & {
    containerUri: string;
     entryIndex: number;
     paramName?: string;
     typeName: string | null;
     /** 当前分页复用的 opaque native session token。 */
     sessionToken?: string;
     /** 写回所需：容器与条目的当前哈希，原样回传即可。 */
    containerHash?: string;
    childHash?: string;
    /**
     * P1：随页下发的字段定义/枚举/授信来源。主进程在 resolveTrustedParamDefinition
     * 里完成 first-party 包校验 + 行宽核对；origin 只给白名单值，渲染器不自行判定。
     */
    fieldDefs?: ParamFieldDef[] | null;
    fieldEnums?: Array<{
      id: string;
      name?: string;
      values: Array<{ value: number; label: string }>;
    }> | null;
    fieldDefsDiagnostic?: { code: string; message: string } | null;
    fieldDefsOrigin?: 'first-party' | 'fixture' | 'imported' | 'user-derived' | null;
    fieldDefsTrusted?: boolean;
  }> =>
    ipcRenderer.invoke('resource.readContainerParamPage', containerUri, entryIndex, page, pageSize, query, loadAll, documentSessionToken),
  readContainerParamRowIndex: (containerUri: string, entryIndex: number): Promise<{
    ok: boolean;
    paramName: string | null;
    typeName: string | null;
    rowDataSize: number;
    rowCount: number;
    rows: Array<{ rowIndex: number; id: number; name?: string; dataHash: string }>;
    rowsTruncated: boolean;
    containerHash: string;
    childHash: string;
    sessionToken?: string;
    authority?: string;
    diagnostics?: Array<{ severity: string; code: string; message: string }>;
  }> =>
    ipcRenderer.invoke('resource.readContainerParamRowIndex', containerUri, entryIndex),
  applyContainerParamFieldMutation: (containerUri: string, expectedContainerHash: string, mutation: {
      entryIndex: number;
      expectedChildHash: string;
      rowIndex: number;
      rowId: number;
      expectedDataHash: string;
      expectedRowDataSize?: number;
      fieldId: string;
      value: number | string | boolean;
      rowDataBase64: string;
      definition: unknown;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyContainerParamFieldMutation', containerUri, expectedContainerHash, mutation),
  applyContainerParamRowNameMutation: (containerUri: string, expectedContainerHash: string, mutation: {
      entryIndex: number;
      expectedChildHash: string;
      rowIndex: number;
      rowId: number;
      expectedDataHash: string;
      expectedRowDataSize?: number;
      name: string;
      rowDataBase64: string;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyContainerParamRowNameMutation', containerUri, expectedContainerHash, mutation),
  applyContainerParamRowMutations: (containerUri: string, expectedContainerHash: string, mutation: {
      kind: 'add' | 'copy' | 'delete';
      entryIndex: number;
      expectedChildHash: string;
      rowId: number;
      rowDataBase64: string;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyContainerParamRowMutations', containerUri, expectedContainerHash, mutation),
  exportParamRowsCsv: (containerUri: string, expectedContainerHash: string, entryIndex: number): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('param.exportRowsCsv', containerUri, expectedContainerHash, entryIndex),
  exportParamNamesCsv: (containerUri: string, expectedContainerHash: string, entryIndex: number): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('param.exportNamesCsv', containerUri, expectedContainerHash, entryIndex),
  importParamNamesCsv: (containerUri: string, expectedContainerHash: string, entryIndex: number, expectedChildHash: string): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('param.importNamesCsv', containerUri, expectedContainerHash, entryIndex, expectedChildHash),
  importParamRowsCsv: (containerUri: string, expectedContainerHash: string, entryIndex: number, expectedChildHash: string): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('param.importRowsCsv', containerUri, expectedContainerHash, entryIndex, expectedChildHash),
  applyParamMutation: (sourceUri: string, expectedHash: string, mutation: {
      kind: 'upsert' | 'delete';
      id: number;
      dataBase64?: string;
      rowIndex?: number;
      expectedDataHash?: string;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyParamMutation', sourceUri, expectedHash, mutation),
  applyParamFieldMutation: (sourceUri: string, expectedHash: string, mutation: {
      rowId: number;
      rowIndex?: number;
      expectedDataHash?: string;
      fieldId: string;
      value: number | string | boolean;
      rowDataBase64: string;
      definition: unknown;
    }): Promise<RendererSaveResult> =>
    ipcRenderer.invoke('resource.applyParamFieldMutation', sourceUri, expectedHash, mutation),
  listAiTools: (): Promise<ToolDescriptor[]> =>
    ipcRenderer.invoke('ai.tools'),
  buildAiSidebarDraft: (request: AiSidebarDraftRequest): Promise<AiSidebarDraft> =>
    ipcRenderer.invoke('ai.sidebarDraft', request),
  runAiTool: (name: string, input: unknown): Promise<ToolResult> =>
    ipcRenderer.invoke('ai.runTool', name, input),
  getMutterNext: (): Promise<MutterNextIpcResult> =>
    ipcRenderer.invoke(AUXILIARY_IPC_CHANNELS.mutterNext),
  getMutterStatus: (): Promise<MutterStatusIpcResult> =>
    ipcRenderer.invoke(AUXILIARY_IPC_CHANNELS.mutterStatus),
  getFeedbackStatus: (): Promise<FeedbackStatusIpcResult> =>
    ipcRenderer.invoke(AUXILIARY_IPC_CHANNELS.feedbackStatus),
  submitSessionFeedback: (input: SessionFeedbackIpcRequest): Promise<SessionFeedbackIpcResult> =>
    ipcRenderer.invoke(AUXILIARY_IPC_CHANNELS.feedbackSubmitSession, input),
  submitAllHistory: (): Promise<SubmitAllHistoryIpcResult> =>
    ipcRenderer.invoke(AUXILIARY_IPC_CHANNELS.feedbackSubmitAll),
  listModelServices: (): Promise<Array<{
    id: string;
    displayName: string;
    protocol: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible';
    baseUrl: string;
    model: string;
    hasCredential: boolean;
    createdAt: string;
    updatedAt: string;
    temperature?: number;
    topP?: number;
    topK?: number;
    maxTokens?: number;
    contextWindowTokens?: number;
    thinkingLevel?: ModelThinkingLevel;
  }>> =>
    ipcRenderer.invoke('modelService.list'),
  getProviderUsageSummary: (): Promise<{
    calls: number;
    reportedCalls: number;
    totalInputTokens: number;
    totalOutputTokens: number;
    firstUsedAt: string | null;
    lastUsedAt: string | null;
    byService: Array<{
      serviceId: string;
      protocol: string;
      model: string;
      calls: number;
      reportedCalls: number;
      totalInputTokens: number;
      totalOutputTokens: number;
      firstUsedAt: string | null;
      lastUsedAt: string | null;
    }>;
    latestSession: null | {
      sessionId: string;
      serviceId: string;
      protocol: string;
      model: string;
      calls: number;
      reportedCalls: number;
      totalInputTokens: number;
      totalOutputTokens: number;
      firstUsedAt: string | null;
      lastUsedAt: string | null;
      lastCallIndex: number;
      currentContextTokens: number;
      contextSource: 'provider' | 'estimated';
      active: boolean;
    };
  }> =>
    ipcRenderer.invoke('modelService.usageSummary'),
  modelServiceEncryptionAvailable: (): Promise<boolean> =>
    ipcRenderer.invoke('modelService.encryptionAvailable'),
  upsertModelService: (input: {
    id?: string;
    displayName: string;
    protocol: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible';
    baseUrl: string;
    model: string;
    apiKey?: string;
    temperature?: number;
    topP?: number;
    topK?: number;
    maxTokens?: number;
    contextWindowTokens?: number;
    thinkingLevel?: ModelThinkingLevel;
  }): Promise<{
    id: string;
    displayName: string;
    protocol: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible';
    baseUrl: string;
    model: string;
    hasCredential: boolean;
    createdAt: string;
    updatedAt: string;
    temperature?: number;
    topP?: number;
    topK?: number;
    maxTokens?: number;
    contextWindowTokens?: number;
    thinkingLevel?: ModelThinkingLevel;
  }> =>
    ipcRenderer.invoke('modelService.upsert', input),
  deleteModelService: (configId: string): Promise<{ ok: true }> =>
    ipcRenderer.invoke('modelService.delete', configId),
  embedWorkspaceRag: (): Promise<| { ok: true; embedded: number; reused: number; failed: number; model: string; dim: number }
    | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('rag.embed'),
  getRagLocalModelStatus: (): Promise<import('@soulforge/shared').RagLocalModelStatus> =>
    ipcRenderer.invoke('rag.localModelStatus'),
  searchWorkspaceEvidence: (input: {
    query: string;
    limit?: number;
    families?: string[];
    expandReferences?: boolean;
  }): Promise<RagRetrieveResult> =>
    ipcRenderer.invoke('rag.searchEvidence', input),
  listModelModels: (input: {
    protocol: 'openai-compatible' | 'openai-responses' | 'anthropic-compatible';
    baseUrl: string;
    apiKey?: string;
  }): Promise<| { ok: true; models: Array<{ id: string; displayName?: string }> }
    | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('modelService.listModels', input),
  runAiAgent: (request: AiAgentRunRequest): Promise<AiAgentRunIpcResult> =>
    ipcRenderer.invoke('ai.agent.run', request),
  requestAiAgentPermission: (mode: 'plan' | 'normal' | 'fullPermission'): Promise<AiAgentPermissionRequestResult> =>
    ipcRenderer.invoke('ai.agent.permission.request', mode),
  getAiAgentEvents: (sessionId: string, afterSeq = 0): Promise<AiAgentEventReplayIpcResult> =>
    ipcRenderer.invoke('ai.agent.events', sessionId, afterSeq),
  cancelAiAgent: (sessionId: string): Promise<AiAgentCancelIpcResult> =>
    ipcRenderer.invoke('ai.agent.cancel', sessionId),
  respondAiAgentApproval: (request: AiAgentApprovalResponseRequest): Promise<{ ok: true; matched: boolean } | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('ai.agent.approval.respond', request),
  listAiAgentSessions: (): Promise<AiAgentSessionListIpcResult> =>
    ipcRenderer.invoke('ai.agent.sessions'),
  loadAiAgentSession: (sessionPath: string): Promise<AiAgentSessionLoadIpcResult> =>
    ipcRenderer.invoke('ai.agent.session.load', sessionPath),
  createAgentResourceReference: (selection: EditorSelectionContext): Promise<AgentResourceReferenceCreateIpcResult> =>
    ipcRenderer.invoke('agent.resourceReference.create', { selection }),
  createAgentCitation: (hits: readonly CiteHit[]): Promise<AgentResourceReferenceCreateIpcResult> =>
    ipcRenderer.invoke('agent.citation.create', { hits }),
  createAgentAttachment: (): Promise<AgentAttachmentCreateIpcResult> =>
    ipcRenderer.invoke('agent.attachment.create'),
  listAiMemories: (): Promise<{ ok: true; entries: MemoryEntry[] } | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('ai.memory.list'),
  saveAiMemory: (entry: { id?: string; topic: string; summary: string; details?: string; tags?: string[] }): Promise<{ ok: true; entry: MemoryEntry } | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('ai.memory.save', entry),
  deleteAiMemory: (idOrTopic: string): Promise<{ ok: true; deleted: boolean } | { ok: false; error: { code: string; message: string } }> =>
    ipcRenderer.invoke('ai.memory.delete', idOrTopic),
  getUpdateState: (): Promise<UpdatePublicState> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.getState),
  setUpdateChannel: (request: UpdateSetChannelRequest): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.setChannel, request),
  checkForUpdate: (): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.check),
  downloadUpdate: (): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.download),
  cancelUpdate: (): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.cancel),
  installUpdate: (): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.install),
  openUpdateRelease: (): Promise<UpdateCommandResult> =>
    ipcRenderer.invoke(UPDATE_IPC_CHANNELS.openRelease),
  onUpdateState: (callback: (value: UpdatePublicState) => void): (() => void) => {
    const listener = (_event: Electron.IpcRendererEvent, envelope: UpdateStateEvent): void => {
      callback(envelope.state);
    };
    ipcRenderer.on(UPDATE_IPC_CHANNELS.event, listener);
    return () => ipcRenderer.removeListener(UPDATE_IPC_CHANNELS.event, listener);
  },
  onAiAgentEvent: (callback: (value: AiAgentEventEnvelope) => void): (() => void) => {
    const listener = (_event: Electron.IpcRendererEvent, envelope: AiAgentEventEnvelope): void => {
      callback(envelope);
    };
    ipcRenderer.on('ai:agent:event', listener);
    return () => { ipcRenderer.removeListener('ai:agent:event', listener); };
  }
};

contextBridge.exposeInMainWorld('soulforge', api);

export type { SoulForgeApi } from '../ipc/publicApi.generated.js';
export type { MapReadCancellationResult } from '../ipc/publicTypes.js';
