// Generated by scripts/generate-public-ipc.mjs. Edit ipc/publicContract.ts instead.
import type { ContractApi } from './contractDefinition.js';
import type { publicIpcContract } from './publicContract.js';

export type SoulForgeApi = ContractApi<typeof publicIpcContract>;
