// Actual resolver bodies with owned files; no native parsing or user corpus.
import assert from 'node:assert/strict';import {readFileSync,existsSync} from 'node:fs';import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';import {join,resolve} from 'node:path';import {tmpdir} from 'node:os';import vm from 'node:vm';import {createRequire} from 'node:module';import test from 'node:test';
const require=createRequire(import.meta.url),ts=require(process.env.SOULFORGE_TEST_TYPESCRIPT_PATH??'typescript');
const rootPath=resolve('apps/desktop/src/main/ipc.ts'),servicePath=resolve('apps/desktop/src/main/services/characterPreviewService.ts'),root=readFileSync(rootPath,'utf8'),service=readFileSync(servicePath,'utf8');
const parse=(path,text)=>ts.createSourceFile(path,text,ts.ScriptTarget.Latest,true),serviceAst=parse(servicePath,service),hasService=serviceAst.statements.some(n=>ts.isFunctionDeclaration(n)&&n.name?.text==='resolveCharacterFlverResource');
const ast=hasService?serviceAst:parse(rootPath,root),names=hasService?['resolveChrbndVirtualResource','resolveCharacterFlverResource']:['resolveChrbndVirtualFile','resolveFlverReadFile'];const bodies=names.map(name=>{const node=ast.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);assert.ok(node,name);return node.getText(ast).replace(/^export\s+/,'');}).join('\n');
async function harness(run){const owned=await mkdtemp(join(tmpdir(),'sf-character-resolver-')),overlay=join(owned,'overlay'),base=join(owned,'base');await mkdir(join(overlay,'chr'),{recursive:true});await mkdir(join(base,'chr'),{recursive:true});let session={layers:{overlayRoot:overlay,baseRoot:base}},files=[];const checks=[];const context={join,existsSync:path=>{checks.push(path);return existsSync(path);},getWorkspaceSession:()=>session,getWorkspaceIndexedFiles:()=>files};vm.createContext(context);vm.runInContext(ts.transpileModule(bodies,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText,context);const ports={getIndexedFiles:()=>files,getActiveSession:()=>session,exists:path=>{checks.push(path);return existsSync(path);}};try{await run({owned,overlay,base,checks,ports,setFiles:value=>{files=value;},setSession:value=>{session=value;},read:uri=>hasService?context.resolveCharacterFlverResource(ports,uri):context.resolveFlverReadFile(uri)});}finally{await rm(owned,{recursive:true,force:true});}}
test('active asset resolver has one implementation in existing character support service',()=>{assert.equal(hasService,true);assert.doesNotMatch(root,/function resolveChrbndVirtualFile\(|function resolveFlverReadFile\(/);assert.match(root,/resolveCharacterFlverResource/);});
test('indexed logical resource wins without filesystem or session lookup',()=>harness(async h=>{const file={sourceUri:'file://owned/model',absolutePath:join(h.owned,'indexed.flver'),relativePath:'indexed.flver'};h.setFiles([file]);h.ports.getActiveSession=()=>{throw new Error('Unneeded session lookup');};assert.deepEqual({...h.read(file.sourceUri)},{absolutePath:file.absolutePath,relativePath:file.relativePath});assert.deepEqual(h.checks,[]);}));
test('unindexed arbitrary URI and traversal/empty segments refuse before filesystem lookup',()=>harness(async h=>{for(const uri of ['file://not-indexed','chrbnd:../outside.chrbnd','chrbnd:chr/../outside.chrbnd','chrbnd:'])assert.equal(h.read(uri),null,uri);assert.deepEqual(h.checks,[]);}));
test('owned overlay companion wins over same base companion',()=>harness(async h=>{const rel='chr/c0000.chrbnd.dcx';await writeFile(join(h.overlay,rel),'owned marker');await writeFile(join(h.base,rel),'owned marker');assert.deepEqual({...h.read(`chrbnd:${rel}`)},{absolutePath:join(h.overlay,rel),relativePath:rel});assert.deepEqual(h.checks,[join(h.overlay,rel)]);}));
test('base companion remains a truthful fallback and missing files return null',()=>harness(async h=>{const rel='chr/c0000.chrbnd.dcx';await writeFile(join(h.base,rel),'owned marker');assert.equal(h.read(`chrbnd:${rel}`).absolutePath,join(h.base,rel));assert.equal(h.read('chrbnd:chr/missing.chrbnd.dcx'),null);}));
test('Windows separators normalize to the same bounded logical companion',()=>harness(async h=>{await writeFile(join(h.overlay,'chr/c0000.chrbnd.dcx'),'owned marker');assert.equal(h.read('chrbnd:chr\\c0000.chrbnd.dcx').relativePath,'chr/c0000.chrbnd.dcx');assert.equal(h.read('chrbnd:chr//c0000.chrbnd.dcx').relativePath,'chr/c0000.chrbnd.dcx');assert.equal(h.read('chrbnd:chr\\..\\escape.chrbnd'),null);}));
test('each lookup uses current host session and index rather than constructor state',()=>harness(async h=>{const rel='chr/c0000.chrbnd.dcx';await writeFile(join(h.overlay,rel),'owned marker');await writeFile(join(h.base,rel),'owned marker');assert.equal(h.read(`chrbnd:${rel}`).absolutePath,join(h.overlay,rel));h.setSession({layers:{overlayRoot:h.base,baseRoot:null}});assert.equal(h.read(`chrbnd:${rel}`).absolutePath,join(h.base,rel));h.setSession(null);assert.equal(h.read(`chrbnd:${rel}`),null);}));
