// Actual document adapter/store/application calls with controlled native ports.
// No Electron/native process or user asset is launched.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { build } from 'esbuild';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import test from 'node:test';
const adapterPath = resolve('apps/desktop/src/main/ipc/documents.ts'), servicePath = resolve('apps/desktop/src/main/services/documentService.ts');
const symbol = Symbol.for('sf.document-domain');
const channels = ['document.open', 'document.get', 'document.page', 'document.readContent', 'document.apply', 'document.close'];
const deferred = () => { let entered, release; return { entered: new Promise(done => { entered = done; }), promise: new Promise(done => { release = done; }), start: () => entered(), release: () => release() }; };
const request = { document: { resourceId: 'file://owned/param/sample.param', domain: 'param', libraryId: 'game-param', bankId: null, documentId: 'sample', sourceVariant: 'overlay' } };
async function harness(run) {
    const root = await mkdtemp(join(tmpdir(), 'sf-document-domain-'));
    const state = { root, handlers: new Map(), reads: [], roots: [], session: { meta: { workspaceId: 'owned' }, layers: { overlayRoot: root } }, sessionId: 'activation-a', file: { sourceUri: request.document.resourceId, absolutePath: join(root, 'sample.param'), relativePath: 'sample.param', resourceKind: 'param', sha256: 'a'.repeat(64) }, rootsGate: null, nativeGate: null, rootsFailure: false, probeFailure: false, probeStatus: 'confirmed' };
    globalThis[symbol] = state;
    try {
        const output = join(root, 'document.mjs'), entry = join(root, 'entry.ts'), coreUrl = pathToFileURL(resolve('packages/core/dist/index.js')).href, sharedUrl = pathToFileURL(resolve('packages/shared/dist/index.js')).href;
        await writeFile(entry, `export * from ${JSON.stringify(adapterPath)};${fs.existsSync(servicePath) ? `export {createDocumentService} from ${JSON.stringify(servicePath)};` : ''}`);
        await build({ entryPoints: [entry], outfile: output, bundle: true, platform: 'node', format: 'esm', external: ['node:*'], plugins: [{ name: 'controlled-document-native', setup(b) {
                        b.onResolve({ filter: /^file:/ }, args => args.path === coreUrl || args.path === sharedUrl ? { path: args.path, external: true } : undefined);
                        b.onResolve({ filter: /^@soulforge\/core$/ }, () => ({ path: 'document-core', namespace: 'fixture' }));
                        b.onLoad({ filter: /document-core/, namespace: 'fixture' }, () => ({ loader: 'js', contents: `export * from ${JSON.stringify(coreUrl)};export async function runBridge(input){const s=globalThis[Symbol.for('sf.document-domain')];s.reads.push(input);if(s.nativeGate){const gate=s.nativeGate;s.nativeGate=null;gate.start();await gate.promise;}return {parseStatus:s.probeFailure?'failed':'confirmed',diagnostics:[],sourceUri:input.resourceUri,data:s.probeFailure?undefined:{outerResourceId:'resource:owned-param',outerHash:'b'.repeat(64),probeStatus:s.probeStatus,reasonCode:null,confirmedStackIds:[],containerRole:'none',leafFormatId:'param',layers:[{layerIndex:0,formatId:'param',entry:null}]}};}` }));
                        b.onResolve({ filter: /^@soulforge\/shared$/ }, () => ({ path: sharedUrl, external: true }));
                        b.onResolve({ filter: /bridgeRoots\.js$/ }, () => ({ path: 'document-roots', namespace: 'fixture' }));
                        b.onLoad({ filter: /document-roots/, namespace: 'fixture' }, () => ({ loader: 'js', contents: `export async function prepareBridgeRoots(session,mode){const s=globalThis[Symbol.for('sf.document-domain')];s.roots.push([session,mode]);if(s.rootsGate){const gate=s.rootsGate;s.rootsGate=null;gate.start();await gate.promise;}return s.rootsFailure?{ok:false,message:'OWNED_ROOTS_FAILURE',details:null}:{ok:true,allowedRoots:[s.root],writableRoots:[s.root]};}` }));
                    } }] });
        const module = await import(pathToFileURL(output).href), deps = { handle: (name, callback) => state.handlers.set(name, callback), get activeSession() { return state.session; }, get activeWorkspaceSessionId() { return state.sessionId; }, get indexedFiles() { return [state.file]; }, durableStoragePaths: () => ({ root, backupBaseDir: root, recoveryDir: root, stagingRoot: root }), bridgeRootSession: (session, storage) => ({ overlayRoot: session.layers.overlayRoot, baseRoot: null, storageRoot: storage.root }) };
        module.registerDocumentIpcHandlers(deps);
        const event = id => ({ sender: { id } });
        await run({ root, state, module, deps, event, invoke: (channel, id, ...args) => state.handlers.get(channel)(event(id), ...args), switchWorkspace(reuse = false) { const old = state.session; state.session = null; module.resetEditorDocumentStore(); state.session = reuse ? old : { meta: { workspaceId: 'owned-b' }, layers: { overlayRoot: root } }; state.sessionId = 'activation-b'; } });
    }
    finally {
        delete globalThis[symbol];
        await rm(root, { recursive: true, force: true });
    }
}
test('document application service owns locator/store orchestration below trusted owner derivation', () => { assert.equal(fs.existsSync(servicePath), true, 'document application service must exist'); const source = fs.readFileSync(servicePath, 'utf8'); assert.doesNotMatch(source, /IpcMainInvokeEvent|TrustedIpcHandle|from ['"]electron|event\.sender/); assert.doesNotMatch(fs.readFileSync(adapterPath, 'utf8'), /await runBridge|buildNativeDocumentLocator|new EditorDocumentStore/); });
test('six existing document channels retain registration order', () => harness(async (h) => assert.deepEqual([...h.state.handlers.keys()], channels)));
test('invalid requests are rejected before roots/native/store admission', () => harness(async (h) => { await assert.rejects(h.invoke('document.open', 1, { document: { resourceId: '/physical' } })); assert.deepEqual(h.state.reads, []); assert.deepEqual(h.state.roots, []); }));
test('absent workspace preserves runtime-blocked refusal', () => harness(async (h) => { h.state.session = null; h.state.sessionId = null; const out = await h.invoke('document.open', 1, request); assert.equal(out.code, 'runtime-blocked'); assert.deepEqual(h.state.reads, []); }));
test('unindexed logical reference and wrong resource domain refuse native dispatch', () => harness(async (h) => { assert.equal((await h.invoke('document.open', 1, { document: { ...request.document, resourceId: 'file://owned/missing' } })).code, 'not-found'); assert.equal((await h.invoke('document.open', 1, { document: { ...request.document, domain: 'texture' } })).code, 'not-found'); assert.deepEqual(h.state.reads, []); }));
test('verified stage roots precede the bounded native locator probe', () => harness(async (h) => { const out = await h.invoke('document.open', 1, request); assert.equal(out.ok, true); assert.equal(h.state.roots[0][1], 'stage'); assert.equal(h.state.reads[0].command, 'probe-document-locator'); assert.equal(h.state.reads[0].timeoutMs, 60000); assert.deepEqual(h.state.reads[0].allowedRoots, [h.root]); assert.equal(h.state.reads[0].filePath, h.state.file.absolutePath); assert.equal(JSON.stringify(out).includes(h.root), false); }));
test('root failure and failed native proof retain precise refusal and no fabricated document', () => harness(async (h) => { h.state.rootsFailure = true; assert.equal((await h.invoke('document.open', 1, request)).code, 'runtime-blocked'); assert.deepEqual(h.state.reads, []); h.state.rootsFailure = false; h.state.probeFailure = true; assert.equal((await h.invoke('document.open', 1, request)).code, 'native-open-failed'); }));
test('blocked/conflicting native locator cannot become an open handle', () => harness(async (h) => { h.state.probeStatus = 'blocked'; assert.equal((await h.invoke('document.open', 1, request)).code, 'runtime-blocked'); h.state.probeStatus = 'conflict'; assert.equal((await h.invoke('document.open', 1, request)).code, 'native-open-failed'); }));
test('actual core store retains same-owner reuse and cross-window handle isolation', () => harness(async (h) => { const first = await h.invoke('document.open', 1, request), again = await h.invoke('document.open', 1, request); assert.equal(first.ok, true); assert.equal(again.value.documentHandle, first.value.documentHandle); assert.equal((await h.invoke('document.get', 2, first.value.documentHandle)).code, 'owner-mismatch'); assert.equal((await h.invoke('document.get', 1, first.value.documentHandle)).ok, true); assert.equal((await h.invoke('document.close', 1, first.value.documentHandle)).ok, true); assert.equal((await h.invoke('document.get', 1, first.value.documentHandle)).code, 'not-found'); }));
test('skeleton read/write ports remain truthful capability/refusal outcomes', () => harness(async (h) => { const out = await h.invoke('document.open', 1, request), documentHandle = out.value.documentHandle, expectedRevision = out.value.revision; const page = await h.invoke('document.page', 1, { documentHandle, expectedRevision, query: { kind: 'param-tables', search: '' }, cursor: null, limit: 20 }); assert.equal(page.code, 'capability-blocked'); const mutation = await h.invoke('document.apply', 1, { documentHandle, expectedRevision, mutation: { kind: 'param-field-set', tableId: 'owned', rowId: '1', fieldId: 'field', value: 2 } }); assert.equal(mutation.ok, false); assert.equal(mutation.code, 'mutation-rejected'); assert.equal((await h.invoke('document.get', 1, documentHandle)).value.revision, expectedRevision); }));
for (const phase of ['roots', 'native'])
    for (const reuse of [false, true])
        test(`document service refuses delayed ${phase} projection after ${reuse ? 'same-object reset' : 'workspace replacement'}`, () => harness(async (h) => { const gate = deferred(); h.state[`${phase}Gate`] = gate; const pending = h.invoke('document.open', 1, request); await gate.entered; h.switchWorkspace(reuse); const current = await h.invoke('document.open', 1, request); assert.equal(current.ok, true); gate.release(); const old = await pending; assert.equal(old.ok, false); assert.equal(old.diagnostics[0].code, 'WORKSPACE_READ_SUPERSEDED'); assert.equal((await h.invoke('document.get', 1, current.value.documentHandle)).ok, true); if (phase === 'roots')
            assert.equal(h.state.reads.length, 1, 'old roots must not dispatch native probe'); }));
const applicationPorts = h => ({ getActiveSession: () => h.state.session, getActiveWorkspaceSessionId: () => h.state.sessionId, getIndexedFiles: () => [h.state.file], durableStoragePaths: h.deps.durableStoragePaths, bridgeRootSession: h.deps.bridgeRootSession });
test('direct document calls retain decoder-first lazy owner admission without registrar or event', () => harness(async (h) => { const service = h.module.createDocumentService(applicationPorts(h)); assert.equal(Object.isFrozen(service), true); assert.deepEqual(Object.keys(service), ['open', 'get', 'page', 'readContent', 'apply', 'close']); let owners = 0; const owner = () => { owners++; return 'owned-main-scope'; }; await assert.rejects(service.open(owner, { bad: true })); assert.equal(owners, 0); assert.equal((await service.get(owner, '')).code, 'invalid-request'); assert.equal((await service.close(owner, '')).code, 'invalid-request'); assert.equal(owners, 0); assert.deepEqual(h.state.reads, []); }));
test('direct document methods preserve actual core ownership, stale revision and unconnected writer refusal', () => harness(async (h) => { const service = h.module.createDocumentService(applicationPorts(h)), owner = () => 'owned-main-a', foreign = () => 'owned-main-b', opened = await service.open(owner, request); assert.equal(opened.ok, true); const documentHandle = opened.value.documentHandle, expectedRevision = opened.value.revision; assert.equal((await service.get(foreign, documentHandle)).code, 'owner-mismatch'); assert.equal((await service.page(owner, { documentHandle, expectedRevision: 'stale', query: { kind: 'param-tables', search: '' }, cursor: null, limit: 20 })).code, 'stale-revision'); assert.equal((await service.readContent(owner, { documentHandle, expectedRevision, query: { kind: 'fmg-content', tableId: 'owned', entryId: '1' } })).code, 'capability-blocked'); assert.equal((await service.apply(owner, { documentHandle, expectedRevision, mutation: { kind: 'param-field-set', tableId: 'owned', rowId: '1', fieldId: 'field', value: 2 } })).code, 'mutation-rejected'); assert.equal((await service.get(owner, documentHandle)).value.revision, expectedRevision); assert.equal((await service.close(owner, documentHandle)).ok, true); }));
test('direct native read uses the same captured lifetime on a same-object reset', () => harness(async (h) => { const service = h.module.createDocumentService(applicationPorts(h)), gate = deferred(); h.state.nativeGate = gate; const old = service.open(() => 'owned-main-a', request); await gate.entered; h.switchWorkspace(true); const fresh = await service.open(() => 'owned-main-b', request); assert.equal(fresh.ok, true); gate.release(); const stopped = await old; assert.equal(stopped.ok, false); assert.equal(stopped.diagnostics[0].code, 'WORKSPACE_READ_SUPERSEDED'); assert.equal((await service.get(() => 'owned-main-b', fresh.value.documentHandle)).ok, true); }));
test('immutable document host ports cannot be replaced while verified roots yield', () => harness(async (h) => { const ports = applicationPorts(h), service = h.module.createDocumentService(ports), gate = deferred(); h.state.rootsGate = gate; const pending = service.open(() => 'owned-main-a', request); await gate.entered; ports.getActiveSession = () => null; ports.getActiveWorkspaceSessionId = () => null; ports.getIndexedFiles = () => []; ports.durableStoragePaths = () => { throw new Error('REPLACED_DOCUMENT_STORAGE'); }; ports.bridgeRootSession = () => { throw new Error('REPLACED_DOCUMENT_ROOTS'); }; gate.release(); assert.equal((await pending).ok, true); assert.equal(h.state.reads.length, 1); }));
