// Actual operation owner/receipt regressions; controlled native transaction ports only.
import assert from 'node:assert/strict';
import test from 'node:test';
import { join } from 'node:path';
import { harness, applicationPorts, gate } from './testing/operationDomainHarness.mjs';
for (const [channel, args] of [['operation.rollback', ['owned-op']], ['operation.rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua']]]) {
    test(`${channel} committed receipt survives a postcommit refresh rejection`, () => harness(async (h) => { const service = h.module.createOperationService({ ...applicationPorts(h), refreshActiveIndexAfterNativeWrite: async () => { throw new Error('refresh owned context C:\\private\\workspace\\file.lua'); } }); const method = channel.endsWith('File') ? 'rollbackFile' : 'rollback'; const out = await service[method](async () => h.state.confirmation, ...args); assert.equal(out.ok, true); assert.equal(out.opId, 'owned-op'); assert.equal(out.inverseOpId, 'owned-inverse'); assert.equal(h.state.native.length, 1); assert.ok(out.diagnostics.some(d => d.severity === 'warning')); assert.equal(JSON.stringify(out).includes('C:\\private'), false); }));
    test(`${channel} pending confirmation cannot borrow a replacement workspace transaction`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(); const method = channel.endsWith('File') ? 'rollbackFile' : 'rollback'; const result = service[method](async () => { pending.start(); await pending.promise; return h.state.confirmation; }, ...args); await pending.entered; h.state.session = { meta: { workspaceId: 'owned-b' }, layers: { overlayRoot: join(h.root, 'b') } }; h.state.store = { get: async () => h.state.operation, history: async () => [] }; pending.release(); const out = await result; assert.equal(out.ok, false); assert.deepEqual(h.state.native, []); }));
    test(`${channel} late committed receipt does not refresh the replacement workspace`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(); h.state.nativeGate = pending; const method = channel.endsWith('File') ? 'rollbackFile' : 'rollback'; const result = service[method](async () => h.state.confirmation, ...args); await pending.entered; h.state.session = { meta: { workspaceId: 'owned-b' }, layers: { overlayRoot: join(h.root, 'b') } }; pending.release(); const out = await result; assert.equal(out.ok, true); assert.equal(out.inverseOpId, 'owned-inverse'); assert.equal(h.state.native.length, 1); assert.deepEqual(h.state.refresh, []); }));
}
for (const [method, args] of [['rollback', ['owned-op']], ['rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua']]])
    for (const phase of ['confirmation', 'native'])
        test(`${method} ${phase} rejects same-session object ABA projection/dispatch`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(); if (phase === 'native')
            h.state.nativeGate = pending; const promise = service[method](async () => { if (phase === 'confirmation') {
            pending.start();
            await pending.promise;
        } return h.state.confirmation; }, ...args); await pending.entered; const original = h.state.session; h.state.session = null; h.state.generation++; h.state.session = original; pending.release(); const out = await promise; if (phase === 'confirmation') {
            assert.equal(out.ok, false);
            assert.deepEqual(h.state.native, []);
        }
        else {
            assert.equal(out.ok, true);
            assert.deepEqual(h.state.refresh, []);
        } }));
for (const [method, args] of [['rollback', ['owned-op']], ['rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua']]])
    test(`${method} receipt labels retain primitive source identity while native settlement yields`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(), originalUri = h.state.files[0].sourceUri; h.state.nativeGate = pending; const promise = service[method](async () => h.state.confirmation, ...args); await pending.entered; h.state.files[0].sourceUri = 'file://replacement/label.lua'; h.state.files[0].relativePath = 'replacement/label.lua'; pending.release(); const out = await promise; assert.deepEqual(out.restoredFiles, [originalUri]); }));
test('same opId under a replacement owner cannot inherit the old owner dedupe refusal', () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(), original = h.state.session; h.state.nativeGate = pending; const old = service.rollback(async () => h.state.confirmation, 'owned-op'); await pending.entered; h.state.session = { meta: { workspaceId: 'owned-b' }, layers: { overlayRoot: join(h.root, 'b') } }; h.state.generation++; h.state.store = { get: async () => h.state.operation, history: async () => [] }; const fresh = await service.rollback(async () => h.state.confirmation, 'owned-op'); assert.equal(fresh.ok, true); assert.equal(h.state.native.length, 2); assert.equal(h.state.native[0][1].session, original); assert.equal(h.state.native[1][1].session, h.state.session); pending.release(); const settled = await old; assert.equal(settled.ok, true); assert.equal(h.state.refresh.length, 1, 'only current owner projects'); assert.equal(h.module.hasActiveRollbackRequests(), false); }));
for (const reuse of [false, true])
    test(`history refuses a delayed ${reuse ? 'same-object ABA' : 'replacement-owner'} projection`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(), logical = { opId: 'owned-op', title: 'Owned', author: 'owned', mode: 'manual', status: 'committed', createdAt: 'owned-date', fileCount: 1, changedPaths: [h.state.physical] }; h.state.store.history = async () => { pending.start(); await pending.promise; return [logical]; }; const history = service.list(); await pending.entered; const original = h.state.session; h.state.session = null; h.state.generation++; h.state.session = reuse ? original : { meta: { workspaceId: 'owned-b' }, layers: { overlayRoot: join(h.root, 'b') } }; h.state.files[0].sourceUri = 'file://replacement/label.lua'; pending.release(); assert.deepEqual(await history, []); }));
for (const [method, args] of [['rollback', ['owned-op']], ['rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua']]])
    test(`${method} postcommit warning masks POSIX error context while retaining the committed carrier`, () => harness(async (h) => { let carrier; const service = h.module.createOperationService({ ...applicationPorts(h), refreshActiveIndexAfterNativeWrite: async (_sources, result) => { carrier = result; throw new Error('refresh denied /private/owned/file.lua retry permitted'); } }); const out = await service[method](async () => h.state.confirmation, ...args); assert.equal(out, carrier); assert.equal(out.ok, true); assert.equal(out.inverseOpId, 'owned-inverse'); assert.equal(out.diagnostics.at(-1).code, 'OPERATION_POSTCOMMIT_REFRESH_FAILED'); assert.equal(JSON.stringify(out).includes('/private/owned'), false); assert.match(out.diagnostics.at(-1).details.message, /refresh denied.*retry permitted/); assert.equal(h.state.native.length, 1); }));
for (const [method, args] of [['rollback', ['owned-op']], ['rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua']]])
    test(`${method} original log cannot be replaced during confirmation`, () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)), pending = gate(); const result = service[method](async () => { pending.start(); await pending.promise; return h.state.confirmation; }, ...args); await pending.entered; h.state.store = { get: async () => h.state.operation, history: async () => [] }; pending.release(); const out = await result; assert.equal(out.ok, false); assert.equal(out.diagnostics[0].code, 'WORKSPACE_ROLLBACK_SUPERSEDED'); assert.deepEqual(h.state.native, []); }));
for(const [method,args]of [['rollback',['owned-op']],['rollbackFile',['owned-op','file://owned/scripts/owned.lua']]])for(const reuse of [false,true])test(`${method} lookup await refuses ${reuse?'ABA':'replacement'} before confirmation/transaction`,()=>harness(async h=>{const service=h.module.createOperationService(applicationPorts(h)),pending=gate();h.state.store.get=async()=>{pending.start();await pending.promise;return h.state.operation;};let confirmed=0;const result=service[method](async()=>{confirmed++;return h.state.confirmation;},...args);await pending.entered;const original=h.state.session;h.state.session=null;h.state.generation++;h.state.session=reuse?original:{meta:{workspaceId:'owned-b'},layers:{overlayRoot:join(h.root,'b')}};pending.release();const out=await result;assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'WORKSPACE_ROLLBACK_SUPERSEDED');assert.equal(confirmed,0);assert.deepEqual(h.state.native,[]);}));
