// Actual operation application/transport controls; native authority is not claimed.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { resolve, join } from 'node:path';
import test from 'node:test';
import { harness, applicationPorts, gate } from './testing/operationDomainHarness.mjs';
const adapterPath = resolve('apps/desktop/src/main/ipc/operations.ts'), servicePath = resolve('apps/desktop/src/main/services/operationService.ts');
test('operation history/rollback orchestration lives below trusted confirmation transport', () => { assert.equal(fs.existsSync(servicePath), true, 'operation application service must exist'); assert.doesNotMatch(fs.readFileSync(servicePath, 'utf8'), /IpcMainInvokeEvent|TrustedIpcHandle|from ['"]electron|event:|_event/); assert.doesNotMatch(fs.readFileSync(adapterPath, 'utf8'), /await rollbackOperation\(|await rollbackFile\(|activeRollbackRequests =|\.filter\(\(entry\)/); });
test('three existing operation channels retain registration order', () => harness(async (h) => assert.deepEqual([...h.state.handlers.keys()], ['operation.list', 'operation.rollback', 'operation.rollbackFile'])));
test('absent session/log refuses rollback before confirmation/native work', () => harness(async (h) => {
    h.state.session = null;
    assert.deepEqual(await h.invoke('operation.list', 1), []);
    for (const [channel, args] of [['operation.rollback', ['owned-op']], ['operation.rollbackFile', ['owned-op', h.state.sourceUri]]]) {
        const result = await h.invoke(channel, 1, ...args);
        assert.equal(result.diagnostics[0].code, 'WORKSPACE_NOT_OPEN');
    }
    assert.deepEqual(h.state.native, []);
    assert.deepEqual(h.state.confirmations, []);
}));
test('history hides inverse implementation records and marks reversed logical operations', () => harness(async (h) => { const logical = { opId: 'owned-op', title: 'Owned', author: 'owned', mode: 'manual', status: 'committed', createdAt: 'owned-date', fileCount: 1, changedPaths: [h.state.physical] }; h.state.history = [logical, { ...logical, opId: 'inverse', inverseOfOpId: 'owned-op' }, { ...logical, opId: 'scoped', rollbackScope: 'file' }]; const history = await h.invoke('operation.list', 1); assert.equal(history.length, 1); assert.equal(history[0].opId, 'owned-op'); assert.equal(history[0].status, 'rolled_back'); assert.equal(JSON.stringify(history).includes(h.root), false); }));
for (const channel of ['operation.rollback', 'operation.rollbackFile'])
    test(`${channel} rejects missing and inverse source operations`, () => harness(async (h) => { const args = channel.endsWith('File') ? ['owned-op', h.state.sourceUri] : ['owned-op']; h.state.operation = null; assert.equal((await h.invoke(channel, 1, ...args)).diagnostics[0].code, 'OPERATION_NOT_FOUND'); h.state.operation = { opId: 'inverse', inverseOfOpId: 'old', files: [] }; assert.equal((await h.invoke(channel, 1, ...args)).diagnostics[0].code, 'ROLLBACK_OF_ROLLBACK_FORBIDDEN'); assert.deepEqual(h.state.confirmations, []); assert.deepEqual(h.state.native, []); }));
test('file rollback rejects an unrelated logical target before admission', () => harness(async (h) => { assert.equal((await h.invoke('operation.rollbackFile', 1, 'owned-op', 'file://owned/missing')).diagnostics[0].code, 'ROLLBACK_FILE_NOT_FOUND'); assert.deepEqual(h.state.confirmations, []); }));
for (const [channel, args, kind] of [['operation.rollback', ['owned-op'], 'operation'], ['operation.rollbackFile', ['owned-op', 'file://owned/scripts/owned.lua'], 'file']]) {
    test(`${channel} keeps lazy event-bound cancellation with no native replay`, () => harness(async (h) => { h.state.confirmation = null; const result = await h.invoke(channel, 7, ...args); assert.equal(result.diagnostics[0].code, 'WRITE_CONFIRMATION_CANCELLED'); assert.equal(h.state.confirmations[0].event.sender.id, 7); assert.deepEqual(h.state.native, []); assert.equal(h.module.hasActiveRollbackRequests(), false); }));
    test(`${channel} preserves exact transaction inputs and one carrier refresh`, () => harness(async (h) => { const out = await h.invoke(channel, 7, ...args), [nativeKind, input] = h.state.native[0]; assert.equal(nativeKind, kind); assert.equal(input.session, h.state.session); assert.equal(input.store, h.store); assert.equal(input.confirmation, h.state.confirmation); assert.equal(input.stagingRoot, join(h.root, 'stage')); assert.equal(h.state.refresh.length, 1); assert.equal(h.state.refresh[0][1], out); assert.equal(out.opId, 'owned-op'); assert.equal(out.inverseOpId, 'owned-inverse'); assert.deepEqual(out.restoredFiles, [h.state.sourceUri]); assert.equal(out.knowledgeRefresh.marker, 'owned'); assert.equal(h.module.hasActiveRollbackRequests(), false); }));
    test(`${channel} deduplicates pending confirmation and cleans up the exact request`, () => harness(async (h) => { const pending = gate(); h.state.confirmGate = pending; const first = h.invoke(channel, 1, ...args); await pending.entered; assert.equal(h.module.hasActiveRollbackRequests(), true); assert.equal((await h.invoke(channel, 1, ...args)).diagnostics[0].code, 'ROLLBACK_IN_PROGRESS'); pending.release(); await first; assert.equal(h.state.native.length, 1); assert.equal(h.module.hasActiveRollbackRequests(), false); }));
}
test('failed/no-change rollback does not refresh and unknown physical paths stay hidden', () => harness(async (h) => { h.state.nativeOk = false; assert.equal((await h.invoke('operation.rollback', 1, 'owned-op')).ok, false); assert.deepEqual(h.state.refresh, []); h.state.nativeOk = true; h.state.restored = false; await h.invoke('operation.rollback', 1, 'owned-op'); assert.deepEqual(h.state.refresh, []); h.state.restored = true; h.state.files = []; assert.deepEqual((await h.invoke('operation.rollback', 1, 'owned-op')).restoredFiles, ['[本机路径已隐藏]']); }));
test('native rejection releases dedupe lease and only a new explicit request can retry', () => harness(async (h) => { h.state.nativeThrows = true; await assert.rejects(h.invoke('operation.rollback', 1, 'owned-op'), /OWNED_NATIVE_FAILURE/); assert.equal(h.module.hasActiveRollbackRequests(), false); assert.equal(h.state.native.length, 1); h.state.nativeThrows = false; assert.equal((await h.invoke('operation.rollback', 1, 'owned-op')).ok, true); assert.equal(h.state.native.length, 2); assert.equal(h.state.confirmations.length, 2); }));
test('direct operation service is finite and requires only admitted confirmation plus host ports', () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)); assert.equal(Object.isFrozen(service), true); assert.deepEqual(Object.keys(service), ['list', 'rollback', 'rollbackFile']); const inputs = [], confirm = async (input) => { inputs.push(input); return h.state.confirmation; }; const out = await service.rollback(confirm, 'owned-op'); assert.equal(out.ok, true); assert.equal('event' in inputs[0], false); assert.deepEqual(inputs[0].extraSubjects, ['ROLLBACK_OPERATION:owned-op']); assert.equal(h.state.native[0][1].confirmation, h.state.confirmation); }));
test('rejected direct rollback does not request confirmation or construct a transaction', () => harness(async (h) => { const service = h.module.createOperationService(applicationPorts(h)); h.state.operation = null; let confirmed = 0; const out = await service.rollbackFile(async () => { confirmed++; return h.state.confirmation; }, 'owned-op', h.state.sourceUri); assert.equal(out.diagnostics[0].code, 'OPERATION_NOT_FOUND'); assert.equal(confirmed, 0); assert.deepEqual(h.state.native, []); }));
test('immutable operation host functions survive a confirmation await', () => harness(async (h) => { const ports = applicationPorts(h), service = h.module.createOperationService(ports), pending = gate(); const request = service.rollback(async () => { pending.start(); await pending.promise; return h.state.confirmation; }, 'owned-op'); await pending.entered; ports.getActiveSession = () => null; ports.getActiveOperationLog = () => null; ports.getIndexedFiles = () => []; ports.durableStoragePaths = () => { throw new Error('REPLACED_ROLLBACK_STORAGE'); }; ports.refreshActiveIndexAfterNativeWrite = () => { throw new Error('REPLACED_ROLLBACK_REFRESH'); }; pending.release(); assert.equal((await request).ok, true); assert.equal(h.state.native[0][1].session, h.state.session); assert.equal(h.state.refresh.length, 1); }));
