// Production RAW service tests with owned filesystem/native ports.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
import { adapterPath, servicePath, names, channels, uri, hash, childHash, file, session, text, nativeEntries, plain, deferred, harness } from './testing/raw-resource-harness.mjs';

test('RAW business and read lifetime are callable below trusted transport',()=>{assert.equal(fs.existsSync(servicePath),true,'RAW application service must exist');assert.doesNotMatch(fs.readFileSync(adapterPath,'utf8'),/runBridge\(|readRawResourceRange\(|containerChildrenCache|scriptContainerEntriesCache/);assert.doesNotMatch(fs.readFileSync(servicePath,'utf8'),/TrustedIpcHandle|IpcMainInvokeEvent|deps\.handle|readLifetime\.register/);});
test('all13 RAW channels retain their original order',()=>assert.deepEqual([...harness().handlers.keys()],channels));
test('direct RAW service enters the captured read lifetime without a registrar',async()=>{
 const start=deferred(),wait=deferred();const h=harness({range:async()=>{start.resolve();await wait.promise;return {ok:true,sourceUri:uri};}});
 const {handle:_handle,...ports}=h.deps;
 const service=h.load(servicePath).createRawResourceService({...ports,get indexedFiles(){return h.deps.indexedFiles;},get activeSession(){return h.deps.activeSession;}});
 assert.equal(Object.isFrozen(service),true);assert.equal('handle' in service,false);
 const pending=service.readRawRange(uri,0,4);await start.promise;h.switchSession({...session});wait.resolve();
 const out=await pending;assert.equal(out.ok,false);assert.equal(out.cancelled,true);assert.equal(out.diagnostics[0].code,'WORKSPACE_READ_SUPERSEDED');
});
test('trusted rejection performs no native/filesystem work',async()=>{const h=harness({deny:true});await assert.rejects(async()=>h.invoke(names[0],uri,0,4),/IPC_UNTRUSTED_SENDER/);assert.deepEqual(h.calls,[]);});
test('unindexed reads return original refusal variants without work',async()=>{const h=harness({files:[]});for(const name of names){const out=await h.invoke(name,uri,0,100);if(['probeContainerCapabilities','readRawMetadata'].includes(name))assert.equal(out,null);else assert.equal(out.ok,false,name);}assert.deepEqual(h.calls,[]);});
test('raw range forwards physical file and exact requested offset/length',async()=>{const h=harness(),out=await h.invoke('readRawRange',uri,5,9);assert.equal(out.fileSize,42);const call=h.calls[0];assert.equal(call[1],file);assert.deepEqual(call.slice(2),[5,9]);});
test('metadata and capabilities strip private physical fields',async()=>{const h=harness();for(const name of ['readRawMetadata','probeContainerCapabilities']){const out=await h.invoke(name,uri);assert.equal(out.sourceUri,uri);assert.equal('absolutePath' in out,false);assert.equal(JSON.stringify(out).includes('/owned/private'),false);}});
test('inspect/child/roundtrip/validation retain native results',async()=>{const h=harness();assert.equal((await h.invoke('inspectContainerTree',uri)).tree.rootHash,hash);assert.equal((await h.invoke('readContainerChild',`${uri}#owned`)).ok,true);assert.equal((await h.invoke('roundTripContainer',uri)).payloadEquivalent,true);assert.equal((await h.invoke('validateContainer',uri)).format,'BND4');});
test('container pages cache the full table and project a bounded safe subset',async()=>{const h=harness(),first=await h.invoke('listContainerChildrenPage',uri,0,100),last=await h.invoke('listContainerChildrenPage',uri,2,100);assert.equal(first.children.length,100);assert.equal(last.children.length,5);assert.equal(first.totalCount,205);assert.equal('absolutePath' in first.children[0],false);assert.equal(h.calls.filter(([n])=>n==='list').length,1);});
test('real container enumeration falls back to complete native entry table',async()=>{const h=harness({nativeFallback:true}),out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,3);assert.equal(out.children[0].name,'goal.lua');assert.equal(out.children[1].name,'goal.lua#1');assert.equal(out.children[0].canReplace,false);assert.equal(JSON.stringify(out).includes('PRIVATE'),false);assert.equal(h.calls.find(([n])=>n==='bridge')[1].command,'read-dcx-document');});
test('loose BND4 enumeration uses its native read-only route, never the DCX reader',async()=>{
 const h=harness({nativeFallback:true,header:Buffer.from('BND4\0\0\0\0'),bridge:input=>input.command==='list-bnd4-entries'?{parseStatus:'partial',diagnostics:[],data:{format:'BND4',entryCount:3,entries:nativeEntries}}:{parseStatus:'failed',diagnostics:[{severity:'error',code:'DCX_DOCUMENT_READ_FAILED',message:'Not a DCX document'}]}});
 const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,true);assert.equal(out.totalCount,3);assert.equal(out.children[0].rawBytesAvailable,false);assert.equal(out.children[0].canReplace,false);assert.deepEqual(h.calls.filter(([n])=>n==='bridge').map(([,input])=>input.command),['list-bnd4-entries']);assert.equal(h.calls.some(([n])=>n==='list'),false);
});
test('loose BND3 reports unsupported instead of routing into DCX or returning an empty success',async()=>{
 const h=harness({nativeFallback:true,header:Buffer.from('BND3\0\0\0\0')});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'BND3_NATIVE_ENUMERATION_UNSUPPORTED');assert.equal(h.calls.some(([n])=>n==='bridge'||n==='list'||n==='readFile'),false);
});
test('large native archive detection reads at most eight bytes and closes the handle',async()=>{
 const h=harness({nativeFallback:true,size:256*1024*1024,readFile:()=>{throw new Error('HEADER_FULL_READ_FORBIDDEN');}});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,3);assert.equal(h.calls.filter(([n])=>n==='readFile'||n==='list').length,0);assert.equal(h.calls.filter(([n])=>n==='headerRead').reduce((sum,call)=>sum+call[3],0),8);assert.equal(h.calls.filter(([n])=>n==='close').length,1);
});
test('short header reads are assembled without reading past the eight-byte probe',async()=>{
 const h=harness({nativeFallback:true,shortRead:2});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,3);const reads=h.calls.filter(([n])=>n==='headerRead');assert.deepEqual(reads.map(call=>call[2]),[0,2,4,6]);assert.equal(reads.reduce((sum,call)=>sum+call[3],0),8);assert.equal(h.calls.filter(([n])=>n==='close').length,1);
});
test('SFBN fixture enumeration retains its existing fixture reader',async()=>{
 const h=harness({header:Buffer.from('BND4SFBN')});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,205);assert.equal(h.calls.some(([n])=>n==='bridge'),false);assert.equal(h.calls.filter(([n])=>n==='list').length,1);
});
test('DCX-wrapped SFBN retains fixture enumeration after the native format refusal',async()=>{
 const h=harness({header:Buffer.from('DCX\0owned'),bridge:()=>({parseStatus:'failed',diagnostics:[{severity:'error',code:'DCX_DOCUMENT_READ_FAILED',message:'Native BND4 header unsupported'}]})});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,true);assert.equal(out.totalCount,205);assert.equal(h.calls.filter(([n])=>n==='list').length,1);
});
test('native DCX payload prefix preserves a wrapped SFBN BND3 fixture',async()=>{
 const h=harness({header:Buffer.from('DCX\0owned'),bridge:()=>({parseStatus:'partial',diagnostics:[],data:{format:'DCX',payloadPrefixHex:'424e44335346424e01000000'}})});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,205);assert.equal(h.calls.filter(([n])=>n==='list').length,1);
});
test('empty native DCX payload does not trigger another full fixture scan',async()=>{
 const h=harness({nativeFallback:true,bridge:()=>({parseStatus:'partial',diagnostics:[],data:{format:'DCX',payloadPrefixHex:'464c564552000000'}})});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,true);assert.equal(out.totalCount,0);assert.equal(h.calls.some(([n])=>n==='list'||n==='readFile'),false);
});
test('native format failure stays a failure when the fixture reader has no children',async()=>{
 const h=harness({nativeFallback:true,bridge:()=>({parseStatus:'failed',diagnostics:[{severity:'error',code:'DCX_DOCUMENT_READ_FAILED',message:'Native header unsupported'}]})});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'DCX_DOCUMENT_READ_FAILED');
});
test('native root refusal cannot fall back to the fixture reader',async()=>{
 const h=harness({header:Buffer.from('DCX\0owned'),bridge:()=>({parseStatus:'failed',diagnostics:[{severity:'error',code:'BRIDGE_PATH_OUTSIDE_ROOTS',message:'Refused'}]})});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,false);assert.equal(h.calls.some(([n])=>n==='list'),false);
});
test('nonpaged loose BND4 listing follows the same native route',async()=>{
 const h=harness({nativeFallback:true,header:Buffer.from('BND4\0\0\0\0'),bridge:input=>({parseStatus:'partial',diagnostics:[],data:{format:'BND4',entryCount:3,entries:nativeEntries}})});const out=await h.invoke('listContainerChildren',uri);assert.equal(out.ok,true);assert.equal(out.children.length,3);assert.equal(h.calls.find(([n])=>n==='bridge')[1].command,'list-bnd4-entries');
});
test('header IO failure is a structured refusal, not a fallback empty success',async()=>{
 const h=harness({nativeFallback:true,openError:new Error('Owned permission refusal')});const out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'CONTAINER_HEADER_READ_FAILED');assert.equal(h.calls.some(([n])=>n==='bridge'||n==='list'),false);
});
test('script evidence verifies staging before the evidence port',async()=>{const h=harness();assert.equal((await h.invoke('scriptContainerEvidence',uri)).ok,true);assert.deepEqual(h.calls.map(([n])=>n),['stageRoots','evidence']);assert.deepEqual(h.calls[1][1].allowedRoots,['/owned/mod']);});
test('script evidence staging refusal does not call native evidence',async()=>{const h=harness({stageDiagnostics:[{severity:'error',code:'OWNED_STAGE_REFUSED',message:'owned'}]});assert.equal((await h.invoke('scriptContainerEvidence',uri)).ok,false);assert.equal(h.calls.filter(([n])=>n==='evidence').length,0);});
test('complete script inventory retains count/classification/index and logical names',async()=>{const h=harness(),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.entriesComplete,true);assert.equal(out.entryCount,3);assert.equal(out.entries[0].index,0);assert.equal(out.entries[1].name,'goal.lua#1');assert.equal(out.classificationSummary['hkx-bytecode'],1);assert.equal(JSON.stringify(out).includes('PRIVATE'),false);await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(h.calls.filter(([n])=>n==='bridge').length,1);});
test('bounded inventory fallback reports incomplete coverage honestly',async()=>{const h=harness({bridge:input=>input.command==='read-dcx-document'?{parseStatus:'failed',diagnostics:[]}:{parseStatus:'confirmed',diagnostics:[],data:{entryCount:30,entries:nativeEntries}}}),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.ok,true);assert.equal(out.entriesComplete,false);assert.equal(out.entryCount,30);assert.equal(out.entries.length,3);});
test('failed complete and inventory reads retain failure diagnostics',async()=>{const h=harness({bridge:()=>({parseStatus:'failed',diagnostics:[{severity:'error',code:'OWNED_NATIVE_REFUSED',message:'owned'}]})}),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'OWNED_NATIVE_REFUSED');});
test('plaintext entry preserves detected encoding and line endings',async()=>{const h=harness(),out=await h.invoke('readScriptEntryPlaintext',uri,'goal.lua');assert.equal(out.isPlaintext,true);assert.equal(out.text,'return 1\r\n');assert.equal(out.newlines.crlf,1);});
test('native indexed script source retains physical entry/hash bindings',async()=>{const h=harness(),out=await h.invoke('readScriptSource',uri,'display-only',0);assert.equal(out.ok,true);assert.equal(out.logicalName,'goal.lua');assert.equal(out.entryIndex,0);assert.equal(out.childHash,childHash);assert.equal(out.containerHash,hash);assert.equal(out.sourceText,'return 1\r\n');const snapshot=h.calls.find(([n,input])=>n==='bridge'&&input.command==='snapshot-bnd4-child')[1];assert.equal(snapshot.commandOptions.entryIndex,0);assert.equal(snapshot.timeoutMs,120000);});
test('invalid native entry index refuses a child snapshot',async()=>{const h=harness(),out=await h.invoke('readScriptSource',uri,'display-only',99);assert.equal(out.ok,false);assert.equal(h.calls.some(([n,input])=>n==='bridge'&&input.command==='snapshot-bnd4-child'),false);});
test('loose script size limit refuses bytes before reading',async()=>{const h=harness({size:64*1024*1024+1}),out=await h.invoke('readScriptSource',uri);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'SCRIPT_SOURCE_TOO_LARGE');assert.equal(h.calls.filter(([n])=>n==='readFile').length,0);});
test('Lua bytecode decompilation keeps first-party dialect and native budgets',async()=>{const h=harness({bytes:Buffer.from([0x1b,0x4c,0x75,0x61,0x51,0])}),out=await h.invoke('readScriptSource',uri);assert.equal(out.kind,'decompiled');assert.equal(out.compiler.origin,'first-party');const input=h.calls.find(([n,input])=>n==='bridge'&&input.command==='read-hks-source')[1];assert.equal(input.maxFrameBytes,32*1024*1024);assert.equal(input.timeoutMs,120000);assert.equal(input.workspaceSessionId,'owned');});
test('unsupported bytecode refuses editable source without HKS native work',async()=>{const h=harness({bytes:Buffer.from([0,1,2,3,4,5])}),out=await h.invoke('readScriptSource',uri);assert.equal(out.writeSupported,false);assert.equal(out.diagnostics[0].code,'SCRIPT_SOURCE_BYTECODE_UNSUPPORTED');assert.equal(h.calls.some(([n])=>n==='bridge'),false);});
for(const phase of ['roots','native'])for(const aba of [false,true])test(`RAW pending ${phase} inventory does not publish into ${aba?'same-object ABA':'replacement'} cache`,async()=>{const start=deferred(),wait=deferred();let old=true;const h=harness({roots:phase==='roots'?async()=>{if(old){start.resolve();await wait.promise;}return {allowedRoots:['/owned/mod'],diagnostics:[]};}:undefined,bridge:async()=>{if(phase==='native'&&old){start.resolve();await wait.promise;}return {parseStatus:'confirmed',diagnostics:[],data:{format:'DCX',nested:{format:'BND4',entryCount:1,entries:[{index:0,name:'current.lua',uncompressedSize:2}]}}};}});const pending=h.invoke('listScriptContainerEntriesPage',uri,0,100);await start.promise;h.switchSession(aba?session:{...session});h.clear();old=false;const current=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(current.ok,true);wait.resolve();const stale=await pending;assert.equal(stale.ok,false);assert.equal(stale.diagnostics[0].code,'WORKSPACE_READ_SUPERSEDED');assert.equal((await h.invoke('listScriptContainerEntriesPage',uri,0,100)).entries[0].name,'current.lua');});
