// Actual RAW/container/script read callbacks with owned synthetic native ports.
// No Electron, native process, game bytes or remote service is used.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {fileURLToPath} from 'node:url';
import test from 'node:test';
import ts from 'typescript';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),require=createRequire(import.meta.url);
const adapterPath=path.join(root,'apps/desktop/src/main/ipc/raw.ts'),servicePath=path.join(root,'apps/desktop/src/main/services/rawResourceService.ts');
const names=['readRawRange','readRawMetadata','inspectContainerTree','listContainerChildren','listContainerChildrenPage','readContainerChild','roundTripContainer','validateContainer','probeContainerCapabilities','scriptContainerEvidence','listScriptContainerEntriesPage','readScriptEntryPlaintext','readScriptSource'];
const channels=names.map(name=>`resource.${name}`),uri='resource://owned/script',hash='a'.repeat(64),childHash='b'.repeat(64);
const file={sourceUri:uri,absolutePath:'/owned/mod/script.luabnd.dcx',relativePath:'script.luabnd.dcx',compoundExtension:'.luabnd.dcx'};
const session={meta:{workspaceId:'owned'},layers:{overlayRoot:'/owned/mod',baseRoot:null}},text=Buffer.from('return 1\r\n');
const nativeEntries=[{index:0,name:'N:\\PRIVATE\\goal.lua',uncompressedSize:10,contentHash:childHash},{index:1,name:'N:\\PRIVATE\\goal.lua',uncompressedSize:10},{index:2,name:'other.hkx',uncompressedSize:5}];
const plain=value=>JSON.parse(JSON.stringify(value));
function deferred(){let resolve;const promise=new Promise(done=>{resolve=done;});return {promise,resolve};}
function harness(options={}){
 const calls=[],handlers=new Map(),modules=new Map();let files=options.files??[file],activeSession=options.session===undefined?session:options.session;
 const children=Array.from({length:205},(_,index)=>({childId:String(index),name:`child${index}`,offset:index,size:1,hash:childHash,formatKind:'lua',sourceContainerUri:uri,childUri:`${uri}#${index}`,rawBytesAvailable:true,canReplace:false,absolutePath:'PRIVATE'}));
 const core={
  runBridge:async input=>{calls.push(['bridge',plain(input)]);if(options.bridge)return options.bridge(input);if(input.command==='snapshot-bnd4-child')return {parseStatus:'confirmed',diagnostics:[],data:{contentBase64:(options.bytes??text).toString('base64')}};if(input.command==='read-hks-source')return {parseStatus:'confirmed',diagnostics:[],data:{sourceText:'return 2',dialect:'sekiro-hks-1.6.x',sourceHash:childHash,compiler:{package:'owned',revision:'owned'},decompiler:{package:'owned',revision:'owned'}}};return {parseStatus:'confirmed',diagnostics:[],data:{format:'DCX',nested:{format:'BND4',entryCount:3,entries:nativeEntries}}};},
  readRawResourceRange:async(readFile,offset,length)=>{calls.push(['rawRange',readFile,offset,length]);if(options.range)return options.range();return {ok:true,sourceUri:readFile.sourceUri,offset,length,fileSize:42};},
  readRawResourceMetadata:async()=>{calls.push(['metadata']);return {sourceUri:uri,absolutePath:'/owned/private',fileSize:42};},
  inspectContainerTree:async()=>{calls.push(['inspect']);return {ok:true,tree:{rootHash:hash}};},
  listContainerChildren:async()=>{calls.push(['list']);return {ok:true,children:options.nativeFallback?[]:children,diagnostics:[]};},
  readContainerChild:async()=>{calls.push(['readChild']);return {ok:true,bytes:options.bytes??text,diagnostics:[]};},
  roundTripContainer:async()=>{calls.push(['roundTrip']);return {ok:true,byteIdentical:true,payloadEquivalent:true};},
  validateContainer:async()=>{calls.push(['validate']);return {ok:true,format:'BND4',diagnostics:[]};},
  probeContainerCapabilityOptions:async()=>{calls.push(['probe']);return {};},
  resolveResourceCapabilities:()=>({sourceUri:uri,absolutePath:'/owned/private',canRead:true}),
  buildScriptContainerEvidence:async input=>{calls.push(['evidence',plain(input)]);return {ok:true,entryCount:3};}
 };
 const shared={createDiagnostic:input=>input};
 const roots={prepareBridgeRoots:async()=>({ok:true,allowedRoots:['/owned/mod'],writableRoots:[]})};
 function load(filename){if(modules.has(filename))return modules.get(filename);const built=ts.transpileModule(fs.readFileSync(filename,'utf8'),{fileName:filename,reportDiagnostics:true,compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.CommonJS}});assert.deepEqual((built.diagnostics??[]).filter(d=>d.category===ts.DiagnosticCategory.Error),[]);const exports={};modules.set(filename,exports);vm.runInNewContext(built.outputText,{exports,module:{exports},Error,Buffer,Uint8Array,ArrayBuffer,TextDecoder,TextEncoder,console,require(name){if(name==='node:fs/promises')return {stat:async()=>({size:options.size??text.length}),readFile:async()=>{calls.push(['readFile']);return options.readFile?options.readFile():options.nativeFallback?Buffer.from('DCX\0owned'):options.bytes??text;}};if(name.startsWith('node:'))return require(name);if(name==='electron')throw new Error('No Electron runtime in RAW services');if(name==='@soulforge/core')return core;if(name==='@soulforge/shared')return shared;if(name.endsWith('/bridgeRoots.js'))return roots;if(name.endsWith('/bridge/runBridge.js'))return {runBridge:core.runBridge};if(name.startsWith('.'))return load(path.resolve(path.dirname(filename),name.replace(/\.js$/,'.ts')));throw new Error(`Unexpected RAW import ${name}`);}},{filename});return exports;}
 Object.assign(shared,load(path.join(root,'packages/shared/src/path-sanitizer.ts')),load(path.join(root,'packages/shared/src/editor-pagination.ts')));
 Object.assign(core,load(path.join(root,'packages/core/src/script/plaintextScriptEntry.ts')),load(path.join(root,'packages/core/src/script/scriptContainerEvidence.ts')));
 core.buildScriptContainerEvidence=async input=>{calls.push(['evidence',plain(input)]);return {ok:true,entryCount:3};};
 core.normalizePageWindow=load(path.join(root,'packages/core/src/editing/editorCapabilityContract.ts')).normalizePageWindow;
 const deps={handle:(name,listener)=>handlers.set(name,(...args)=>{if(options.deny)throw new Error('IPC_UNTRUSTED_SENDER');return listener(...args);}),get indexedFiles(){return files;},get activeSession(){return activeSession;},durableStoragePaths:()=>({root:'/owned/storage',backupBaseDir:'/owned/backup',recoveryDir:'/owned/recovery',stagingRoot:'/owned/stage'}),bridgeRootSession:()=>({}),bridgeRootsDiagnostic:(code)=>({severity:'error',code,message:'owned'}),verifiedReadRoots:async()=>{calls.push(['roots']);return options.roots?options.roots():{allowedRoots:['/owned/mod'],diagnostics:options.rootDiagnostics??[]};},verifiedStageRoots:async()=>{calls.push(['stageRoots']);return {allowedRoots:['/owned/mod'],writableRoots:['/owned/stage'],diagnostics:options.stageDiagnostics??[]};}};
 const adapter=load(adapterPath);adapter.registerRawIpcHandlers(deps);
 return {calls,handlers,load,deps,adapter,invoke:(name,...args)=>handlers.get(`resource.${name}`)({},...args),switchSession(value){activeSession=value;},clear(){adapter.clearRawIpcCaches();}};
}

test('RAW business and read lifetime are callable below trusted transport',()=>{assert.equal(fs.existsSync(servicePath),true,'RAW application service must exist');assert.doesNotMatch(fs.readFileSync(adapterPath,'utf8'),/runBridge\(|readRawResourceRange\(|containerChildrenCache|scriptContainerEntriesCache/);assert.doesNotMatch(fs.readFileSync(servicePath,'utf8'),/TrustedIpcHandle|IpcMainInvokeEvent|deps\.handle|readLifetime\.register/);});
test('all13 RAW channels retain their original order',()=>assert.deepEqual([...harness().handlers.keys()],channels));
test('direct RAW service enters the captured read lifetime without a registrar',async()=>{
 const start=deferred(),wait=deferred();const h=harness({range:async()=>{start.resolve();await wait.promise;return {ok:true,sourceUri:uri};}});
 const {handle:_handle,...ports}=h.deps;
 const service=h.load(servicePath).createRawResourceService({...ports,get indexedFiles(){return h.deps.indexedFiles;},get activeSession(){return h.deps.activeSession;}});
 assert.equal(Object.isFrozen(service),true);assert.equal('handle' in service,false);
 const pending=service.readRawRange(uri,0,4);await start.promise;h.switchSession({...session});wait.resolve();
 const out=await pending;assert.equal(out.ok,false);assert.equal(out.cancelled,true);assert.equal(out.diagnostics[0].code,'WORKSPACE_READ_SUPERSEDED');
});
test('trusted rejection performs no native/filesystem work',async()=>{const h=harness({deny:true});await assert.rejects(async()=>h.invoke(names[0],uri,0,4),/IPC_UNTRUSTED_SENDER/);assert.deepEqual(h.calls,[]);});
test('unindexed reads return original refusal variants without work',async()=>{const h=harness({files:[]});for(const name of names){const out=await h.invoke(name,uri,0,100);if(['probeContainerCapabilities','readRawMetadata'].includes(name))assert.equal(out,null);else assert.equal(out.ok,false,name);}assert.deepEqual(h.calls,[]);});
test('raw range forwards physical file and exact requested offset/length',async()=>{const h=harness(),out=await h.invoke('readRawRange',uri,5,9);assert.equal(out.fileSize,42);const call=h.calls[0];assert.equal(call[1],file);assert.deepEqual(call.slice(2),[5,9]);});
test('metadata and capabilities strip private physical fields',async()=>{const h=harness();for(const name of ['readRawMetadata','probeContainerCapabilities']){const out=await h.invoke(name,uri);assert.equal(out.sourceUri,uri);assert.equal('absolutePath' in out,false);assert.equal(JSON.stringify(out).includes('/owned/private'),false);}});
test('inspect/child/roundtrip/validation retain native results',async()=>{const h=harness();assert.equal((await h.invoke('inspectContainerTree',uri)).tree.rootHash,hash);assert.equal((await h.invoke('readContainerChild',`${uri}#owned`)).ok,true);assert.equal((await h.invoke('roundTripContainer',uri)).payloadEquivalent,true);assert.equal((await h.invoke('validateContainer',uri)).format,'BND4');});
test('container pages cache the full table and project a bounded safe subset',async()=>{const h=harness(),first=await h.invoke('listContainerChildrenPage',uri,0,100),last=await h.invoke('listContainerChildrenPage',uri,2,100);assert.equal(first.children.length,100);assert.equal(last.children.length,5);assert.equal(first.totalCount,205);assert.equal('absolutePath' in first.children[0],false);assert.equal(h.calls.filter(([n])=>n==='list').length,1);});
test('real container enumeration falls back to complete native entry table',async()=>{const h=harness({nativeFallback:true}),out=await h.invoke('listContainerChildrenPage',uri,0,100);assert.equal(out.totalCount,3);assert.equal(out.children[0].name,'goal.lua');assert.equal(out.children[1].name,'goal.lua#1');assert.equal(out.children[0].canReplace,false);assert.equal(JSON.stringify(out).includes('PRIVATE'),false);assert.equal(h.calls.find(([n])=>n==='bridge')[1].command,'read-dcx-document');});
test('script evidence verifies staging before the evidence port',async()=>{const h=harness();assert.equal((await h.invoke('scriptContainerEvidence',uri)).ok,true);assert.deepEqual(h.calls.map(([n])=>n),['stageRoots','evidence']);assert.deepEqual(h.calls[1][1].allowedRoots,['/owned/mod']);});
test('script evidence staging refusal does not call native evidence',async()=>{const h=harness({stageDiagnostics:[{severity:'error',code:'OWNED_STAGE_REFUSED',message:'owned'}]});assert.equal((await h.invoke('scriptContainerEvidence',uri)).ok,false);assert.equal(h.calls.filter(([n])=>n==='evidence').length,0);});
test('complete script inventory retains count/classification/index and logical names',async()=>{const h=harness(),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.entriesComplete,true);assert.equal(out.entryCount,3);assert.equal(out.entries[0].index,0);assert.equal(out.entries[1].name,'goal.lua#1');assert.equal(out.classificationSummary['hkx-bytecode'],1);assert.equal(JSON.stringify(out).includes('PRIVATE'),false);await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(h.calls.filter(([n])=>n==='bridge').length,1);});
test('bounded inventory fallback reports incomplete coverage honestly',async()=>{const h=harness({bridge:input=>input.command==='read-dcx-document'?{parseStatus:'failed',diagnostics:[]}:{parseStatus:'confirmed',diagnostics:[],data:{entryCount:30,entries:nativeEntries}}}),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.ok,true);assert.equal(out.entriesComplete,false);assert.equal(out.entryCount,30);assert.equal(out.entries.length,3);});
test('failed complete and inventory reads retain failure diagnostics',async()=>{const h=harness({bridge:()=>({parseStatus:'failed',diagnostics:[{severity:'error',code:'OWNED_NATIVE_REFUSED',message:'owned'}]})}),out=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'OWNED_NATIVE_REFUSED');});
test('plaintext entry preserves detected encoding and line endings',async()=>{const h=harness(),out=await h.invoke('readScriptEntryPlaintext',uri,'goal.lua');assert.equal(out.isPlaintext,true);assert.equal(out.text,'return 1\r\n');assert.equal(out.newlines.crlf,1);});
test('native indexed script source retains physical entry/hash bindings',async()=>{const h=harness(),out=await h.invoke('readScriptSource',uri,'display-only',0);assert.equal(out.ok,true);assert.equal(out.logicalName,'goal.lua');assert.equal(out.entryIndex,0);assert.equal(out.childHash,childHash);assert.equal(out.containerHash,hash);assert.equal(out.sourceText,'return 1\r\n');const snapshot=h.calls.find(([n,input])=>n==='bridge'&&input.command==='snapshot-bnd4-child')[1];assert.equal(snapshot.commandOptions.entryIndex,0);assert.equal(snapshot.timeoutMs,120000);});
test('invalid native entry index refuses a child snapshot',async()=>{const h=harness(),out=await h.invoke('readScriptSource',uri,'display-only',99);assert.equal(out.ok,false);assert.equal(h.calls.some(([n,input])=>n==='bridge'&&input.command==='snapshot-bnd4-child'),false);});
test('loose script size limit refuses bytes before reading',async()=>{const h=harness({size:64*1024*1024+1}),out=await h.invoke('readScriptSource',uri);assert.equal(out.ok,false);assert.equal(out.diagnostics[0].code,'SCRIPT_SOURCE_TOO_LARGE');assert.equal(h.calls.filter(([n])=>n==='readFile').length,0);});
test('Lua bytecode decompilation keeps first-party dialect and native budgets',async()=>{const h=harness({bytes:Buffer.from([0x1b,0x4c,0x75,0x61,0x51,0])}),out=await h.invoke('readScriptSource',uri);assert.equal(out.kind,'decompiled');assert.equal(out.compiler.origin,'first-party');const input=h.calls.find(([n,input])=>n==='bridge'&&input.command==='read-hks-source')[1];assert.equal(input.maxFrameBytes,32*1024*1024);assert.equal(input.timeoutMs,120000);assert.equal(input.workspaceSessionId,'owned');});
test('unsupported bytecode refuses editable source without HKS native work',async()=>{const h=harness({bytes:Buffer.from([0,1,2,3,4,5])}),out=await h.invoke('readScriptSource',uri);assert.equal(out.writeSupported,false);assert.equal(out.diagnostics[0].code,'SCRIPT_SOURCE_BYTECODE_UNSUPPORTED');assert.equal(h.calls.some(([n])=>n==='bridge'),false);});
for(const phase of ['roots','native'])for(const aba of [false,true])test(`RAW pending ${phase} inventory does not publish into ${aba?'same-object ABA':'replacement'} cache`,async()=>{const start=deferred(),wait=deferred();let old=true;const h=harness({roots:phase==='roots'?async()=>{if(old){start.resolve();await wait.promise;}return {allowedRoots:['/owned/mod'],diagnostics:[]};}:undefined,bridge:async()=>{if(phase==='native'&&old){start.resolve();await wait.promise;}return {parseStatus:'confirmed',diagnostics:[],data:{format:'DCX',nested:{format:'BND4',entryCount:1,entries:[{index:0,name:'current.lua',uncompressedSize:2}]}}};}});const pending=h.invoke('listScriptContainerEntriesPage',uri,0,100);await start.promise;h.switchSession(aba?session:{...session});h.clear();old=false;const current=await h.invoke('listScriptContainerEntriesPage',uri,0,100);assert.equal(current.ok,true);wait.resolve();const stale=await pending;assert.equal(stale.ok,false);assert.equal(stale.diagnostics[0].code,'WORKSPACE_READ_SUPERSEDED');assert.equal((await h.invoke('listScriptContainerEntriesPage',uri,0,100)).entries[0].name,'current.lua');});
