// Actual root/destroy/transport callbacks; no Electron process or user data.
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {basename,resolve} from 'node:path';
import {createRequire} from 'node:module';
import vm from 'node:vm';
import test from 'node:test';
const require=createRequire(import.meta.url),ts=require(process.env.SOULFORGE_TEST_TYPESCRIPT_PATH??'typescript');
const path=resolve('apps/desktop/src/main/ipc.ts'),source=readFileSync(path,'utf8'),ast=ts.createSourceFile(path,source,ts.ScriptTarget.Latest,true);
const retired=new Set(['activeRollbackRequests','logicalMapModelName','resolveMapModelFile','DirectorySelectionRecord','directorySelections','editorDocumentStore','ensureEditorDocumentStore','deriveDocumentOwnerKey','DOMAIN_RESOURCE_KINDS','editorDocumentFailure','createDirectorySelection','consumeDirectorySelection']);
const fn=(file,name)=>file.statements.find(n=>ts.isFunctionDeclaration(n)&&n.name?.text===name);
const transpile=text=>ts.transpileModule(text,{compilerOptions:{target:ts.ScriptTarget.ES2022,module:ts.ModuleKind.None}}).outputText;
function destroyScope(){const register=fn(ast,'registerIpcHandlers'),callbacks=[];const visit=n=>{if(ts.isCallExpression(n)&&n.expression.getText(ast)==='webContents.once'&&n.arguments[0]?.text==='destroyed')callbacks.push(n.arguments[1]);ts.forEachChild(n,visit);};visit(register);assert.equal(callbacks.length,1);const workspacePath=resolve('apps/desktop/src/main/ipc/workspace.ts'),workspace=ts.createSourceFile(workspacePath,readFileSync(workspacePath,'utf8'),ts.ScriptTarget.Latest,true),names=['createDirectorySelection','consumeDirectorySelection','revokeDirectorySelectionsFor'];const scope={trustedRendererDocuments:new Map([[17,'file:///owned/index.html'],[18,'file:///owned/index.html']]),directorySelections:new Map(),disposed:[],webContents:{id:17},basename,Date,randomUUID:(()=>{let next=0;return ()=>`owned-selection-${++next}`;})()};scope.disposeEmevdWindow=id=>scope.disposed.push(id);vm.createContext(scope);vm.runInContext(transpile(names.map(name=>fn(workspace,name).getText(workspace).replace(/^export\s+/, '')).join('\n')),scope);return {scope,callback:vm.runInContext(`(${transpile(callbacks[0].getText(ast)).replace(/;\s*$/,'')})`,scope)};}
test('root has no second local document/map/selection/rollback domain owner',()=>{const definitions=ast.statements.flatMap(n=>ts.isVariableStatement(n)?[...n.declarationList.declarations]:[n]).filter(n=>n.name&&retired.has(n.name.getText(ast)));assert.deepEqual(definitions.map(n=>n.name.getText(ast)),[]);});
test('actual destroyed callback revokes only that window real workspace credentials and event slot',()=>{const {scope,callback}=destroyScope(),a=scope.createDirectorySelection({sender:{id:17}},'/owned/a','overlay'),b=scope.createDirectorySelection({sender:{id:18}},'/owned/b','base');callback();assert.equal(scope.trustedRendererDocuments.has(17),false);assert.equal(scope.trustedRendererDocuments.has(18),true);assert.deepEqual(scope.disposed,[17]);assert.throws(()=>scope.consumeDirectorySelection({sender:{id:17}},a.selectionId,'overlay'),/目录选择凭据/);assert.equal(scope.consumeDirectorySelection({sender:{id:18}},b.selectionId,'base').label,'b');});
test('actual trusted transport rejects foreign frames/documents before listener and keeps projection',async()=>{let listenerCalls=0,sanitized=0;const handlers=new Map(),scope={URL,trustedRendererDocuments:new Map([[17,'file:///owned/index.html']]),ipcMain:{handle:(channel,callback)=>handlers.set(channel,callback)},sanitizeRendererValue:result=>{sanitized++;return {value:result.value};}};vm.createContext(scope);vm.runInContext(transpile(['normalizeRendererDocumentUrl','assertTrustedSender','handle'].map(name=>fn(ast,name).getText(ast)).join('\n')),scope);scope.handle('owned.test',async()=>{listenerCalls++;return {value:'logical',absolutePath:'/hidden'};});const frame={url:'file:///owned/index.html?view=1#panel'},sender={id:17,mainFrame:frame},call=handlers.get('owned.test');await assert.rejects(call({sender,senderFrame:{url:frame.url}}),/不受信任/);await assert.rejects(call({sender,senderFrame:{url:'file:///foreign/index.html'}}),/不受信任/);assert.equal(listenerCalls,0);assert.deepEqual({...await call({sender,senderFrame:frame})},{value:'logical'});assert.equal(listenerCalls,1);assert.equal(sanitized,1);});
