// Actual workspace adapter/application calls with owned directories and host seams.
// No Electron/native/ME3 process, user game corpus or real database is launched.
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { build } from 'esbuild';
import { mkdtemp, mkdir, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import test from 'node:test';
const servicePath = resolve('apps/desktop/src/main/services/workspaceService.ts'), adapterPath = resolve('apps/desktop/src/main/ipc/workspace.ts');
const channels = ['runtime.detectMe3', 'runtime.prepareMe3Profile', 'runtime.launchMe3', 'runtime.terminateMe3', 'workspace.lastSelection', 'workspace.openDialog', 'workspace.openBaseDialog', 'workspace.scan', 'workspace.remountBase', 'workspace.analyze'];
const key = Symbol.for('sf.workspace-domain-service');
async function harness(run) {
    const root = await mkdtemp(join(tmpdir(), 'sf-workspace-domain-')), overlay = join(root, 'overlay'), base = join(root, 'base');
    await mkdir(overlay);
    await mkdir(base);
    const calls = [], handlers = new Map(), state = { root, overlay, base, calls, dialogCancelled: false, dialogPath: overlay };
    globalThis[key] = state;
    try {
        const output = join(root, 'workspace.mjs'), entry = join(root, 'entry.ts'), core = resolve('packages/core/dist/index.js'), coreUrl = pathToFileURL(core).href;
        await writeFile(entry, `export * from ${JSON.stringify(adapterPath)};export {createWorkspaceService,__testPersistActiveRag} from ${JSON.stringify(servicePath)};export {createWorkspaceRuntimeService} from ${JSON.stringify(resolve('apps/desktop/src/main/services/workspaceRuntimeService.ts'))};`);
        await build({ entryPoints: [entry], outfile: output, bundle: true, format: 'esm', platform: 'node', external: ['node:*'], plugins: [{ name: 'owned-workspace-host', setup(b) { b.onLoad({filter:/workspaceService\.ts$/},args=>({loader:'ts',contents:fs.readFileSync(args.path,'utf8')+'\n// Test-only access to the actual private publication callback.\nexport {persistActiveRag as __testPersistActiveRag};\n'})); b.onResolve({ filter: /^file:/ }, args => args.path === coreUrl ? { path: coreUrl, external: true } : undefined); b.onResolve({ filter: /^@soulforge\/core$/ }, () => ({ path: 'core-host', namespace: 'owned' })); b.onResolve({ filter: /^@soulforge\/shared$/ }, () => ({ path: pathToFileURL(resolve('packages/shared/dist/index.js')).href, external: true })); b.onLoad({ filter: /core-host/, namespace: 'owned' }, () => ({ loader: 'js', contents: `export * from ${JSON.stringify(coreUrl)};const state=()=>globalThis[Symbol.for('sf.workspace-domain-service')];export class Me3RuntimeAdapter{constructor(input){this.input=input;}async detect(input){state().calls.push(['detect',input]);return {ok:true,marker:'owned'};}async prepareProfile(input,options){state().calls.push(['prepareProfile',input,options]);return {ok:true};}async launch(input,options){state().calls.push(['launch',input,options]);return {ok:true};}async terminate(input,options){state().calls.push(['terminate',input,options]);return {ok:true};}}` })); b.onResolve({ filter: /^electron$/ }, () => ({ path: 'electron-host', namespace: 'owned' })); b.onLoad({ filter: /electron-host/, namespace: 'owned' }, () => ({ loader: 'js', contents: `const state=()=>globalThis[Symbol.for('sf.workspace-domain-service')];export const app={isPackaged:false,getPath:()=>state().root,getAppPath:()=>state().root};export const dialog={showOpenDialog:async()=>({canceled:state().dialogCancelled,filePaths:[state().dialogPath]})};export const utilityProcess={fork(){throw new Error('No process in workspace fixture');}};` })); } }] });
        const module = await import(pathToFileURL(output).href);
        let releaseError = false;
        const deps = { handle: (name, callback) => handlers.set(name, callback), clearActiveOperationLog: async () => calls.push(['closeDatabase']), releaseEditorCaches: () => { assert.equal(module.getWorkspaceSession(), null); calls.push(['releaseViews']); if (releaseError)
                throw new Error('OWNED_RELEASE_FRONTIER'); }, ensureActiveOperationLog: async () => { calls.push(['openDatabase']); throw new Error('OWNED_DATABASE_UNAVAILABLE'); }, verifiedReadRoots: async () => ({ allowedRoots: [root], diagnostics: [] }) };
        module.registerWorkspaceIpcHandlers(deps);
        const event = id => ({ sender: { id } });
        await run({ root, overlay, base, calls, handlers, state, module, deps, event, invoke: (channel, id, ...args) => handlers.get(channel)(event(id), ...args), stopAtRelease() { releaseError = true; } });
    }
    finally {
        delete globalThis[key];
        await rm(root, { recursive: true, force: true });
    }
}
test('workspace state/index/jobs live in callable services below sender-bound directory transport', () => { assert.equal(fs.existsSync(servicePath), true, 'Workspace application service must exist'); const adapter = fs.readFileSync(adapterPath, 'utf8'); assert.doesNotMatch(adapter, /await scanWorkspace\(|await analyzeWorkspace\(|workspaceAnalyzeInFlight|fingerprintStore\.hashes/); assert.doesNotMatch(fs.readFileSync(servicePath, 'utf8'), /IpcMainInvokeEvent|TrustedIpcHandle|from ['"]electron|ownerWebContentsId|directorySelections/); });
test('all ten existing runtime/workspace channels retain registration order', () => harness(async (h) => assert.deepEqual([...h.handlers.keys()], channels)));
test('cancelled directory dialog creates no selection credential', () => harness(async (h) => { h.state.dialogCancelled = true; assert.equal(await h.invoke('workspace.openDialog', 1), null); assert.deepEqual(h.calls, []); }));
test('wrong-window and consumed directory credentials cannot scan', () => harness(async (h) => { const selected = await h.invoke('workspace.openDialog', 1); await assert.rejects(h.invoke('workspace.scan', 2, { overlaySelectionId: selected.selectionId }), /目录选择凭据/); await assert.rejects(h.invoke('workspace.scan', 1, { overlaySelectionId: selected.selectionId }), /目录选择凭据/); assert.deepEqual(h.calls, []); }));
test('expired directory credential is rejected before database or scan work', () => harness(async (h) => { const selected = await h.invoke('workspace.openDialog', 1), now = Date.now; Date.now = () => now() + 6 * 60000; try {
    await assert.rejects(h.invoke('workspace.scan', 1, { overlaySelectionId: selected.selectionId }), /目录选择凭据/);
}
finally {
    Date.now = now;
} assert.deepEqual(h.calls, []); }));
test('window revocation removes only its own outstanding selections', () => harness(async (h) => { const first = await h.invoke('workspace.openDialog', 1), second = await h.invoke('workspace.openDialog', 2); h.module.revokeDirectorySelectionsFor(1); await assert.rejects(h.invoke('workspace.scan', 1, { overlaySelectionId: first.selectionId }), /目录选择凭据/); assert.equal((await h.invoke('workspace.scan', 2, { overlaySelectionId: second.selectionId, clearBase: true })).session.baseMounted, false); }));
test('scan detaches old session and releases views before light logical response', () => harness(async (h) => { const selected = await h.invoke('workspace.openDialog', 1); const result = await h.invoke('workspace.scan', 1, { overlaySelectionId: selected.selectionId, clearBase: true }); assert.deepEqual(h.calls.slice(0, 2).map(([n]) => n), ['closeDatabase', 'releaseViews']); assert.ok(result.workspaceSessionId); assert.equal(result.session.workspaceLabel, 'overlay'); assert.equal(JSON.stringify(result).includes(h.root), false); assert.equal(h.module.getWorkspaceSession().layers.overlayRoot, h.overlay); assert.equal(result.files.length, 0); }));
test('explicit base selection preserves physical session mount and logical label', () => harness(async (h) => { const overlay = await h.invoke('workspace.openDialog', 1); h.state.dialogPath = h.base; const base = await h.invoke('workspace.openBaseDialog', 1); const result = await h.invoke('workspace.scan', 1, { overlaySelectionId: overlay.selectionId, baseSelectionId: base.selectionId }); assert.equal(h.module.getWorkspaceSession().layers.baseRoot, h.base); assert.equal(result.session.baseLabel, 'base'); assert.equal(JSON.stringify(result).includes(h.root), false); }));
test('remount preserves overlay, increments activation and releases old views first', () => harness(async (h) => { const selected = await h.invoke('workspace.openDialog', 1); await h.invoke('workspace.scan', 1, { overlaySelectionId: selected.selectionId, clearBase: true }); const old = h.module.getWorkspaceSession(), generation = h.module.getActiveWorkspaceSessionGenerationState(); h.stopAtRelease(); await assert.rejects(h.invoke('workspace.remountBase', 1), /OWNED_RELEASE_FRONTIER/); assert.equal(h.module.getWorkspaceSession(), null); assert.deepEqual(h.calls.slice(-2).map(([n]) => n), ['closeDatabase', 'releaseViews']); assert.ok(old.layers.overlayRoot); assert.equal(h.module.getActiveWorkspaceSessionGenerationState(), generation); }));
test('analyze requires an active workspace and does not start native work', () => harness(async (h) => { await assert.rejects(h.invoke('workspace.analyze', 1), /请先打开工作区/); assert.deepEqual(h.calls, []); }));
test('runtime profile/launch refuse absent workspace before host operation', () => harness(async (h) => { assert.equal((await h.invoke('runtime.prepareMe3Profile', 1)).diagnostics[0].code, 'RUNTIME_NO_WORKSPACE'); assert.equal((await h.invoke('runtime.launchMe3', 1, 'owned-profile')).diagnostics[0].code, 'RUNTIME_NO_WORKSPACE'); assert.deepEqual(h.calls, []); }));
test('runtime detect retains fixed host timeout with no real process', () => harness(async (h) => { assert.equal((await h.invoke('runtime.detectMe3', 1)).marker, 'owned'); assert.deepEqual(h.calls, [['detect', { timeoutMs: 5000 }]]); }));
test('wrong-kind base credential fails before workspace lifecycle changes', () => harness(async (h) => { const overlay = await h.invoke('workspace.openDialog', 1), wrongBase = await h.invoke('workspace.openDialog', 1); await assert.rejects(h.invoke('workspace.scan', 1, { overlaySelectionId: overlay.selectionId, baseSelectionId: wrongBase.selectionId }), /目录选择凭据/); assert.deepEqual(h.calls, []); }));
test('automatic project base passes through the same trusted credential admission', () => harness(async (h) => { await writeFile(join(h.overlay, 'project.json'), JSON.stringify({ GameRoot: '../base' })); await writeFile(join(h.base, 'sekiro.exe'), 'owned marker; never executed'); const overlay = await h.invoke('workspace.openDialog', 1), out = await h.invoke('workspace.scan', 1, { overlaySelectionId: overlay.selectionId }); assert.equal(h.module.getWorkspaceSession().layers.baseRoot, h.base); assert.equal(out.session.baseMounted, true); assert.equal(out.session.baseLabel, undefined); assert.equal(JSON.stringify(out).includes(h.root), false); }));
test('direct workspace application calls require only admitted selection and host ports', () => harness(async (h) => { const { handle: _handle, ...ports } = h.deps; const service = h.module.createWorkspaceService({ ...ports, resolveWorkspaceStoragePaths: () => ({ root: join(h.root, 'store'), backupBaseDir: join(h.root, 'backup'), recoveryDir: join(h.root, 'recovery'), stagingRoot: join(h.root, 'staging'), isCompanion: false }), clearRememberedBase: () => { } }); assert.equal(Object.isFrozen(service), true); assert.equal('handle' in service, false); const out = await service.scan({ overlaySelectionId: 'logical-unused', clearBase: true }, () => Object.freeze({ absolutePath: h.overlay, label: 'direct', kind: 'overlay' }), () => undefined, () => { throw new Error('Auto base must be disabled'); }); assert.equal(out.workspaceLabel, 'direct'); assert.equal(JSON.stringify(out).includes(h.root), false); }));
test('runtime profile and launch retain admitted session identity and exact existing deadlines', () => harness(async (h) => { const selected = await h.invoke('workspace.openDialog', 1); await h.invoke('workspace.scan', 1, { overlaySelectionId: selected.selectionId, clearBase: true }); const id = h.module.getActiveWorkspaceSessionIdState(); await h.invoke('runtime.prepareMe3Profile', 1); await h.invoke('runtime.launchMe3', 1, 'owned-profile'); await h.invoke('runtime.terminateMe3', 1, 'owned-runtime'); const prepared = h.calls.find(([name]) => name === 'prepareProfile'), launched = h.calls.find(([name]) => name === 'launch'), terminated = h.calls.find(([name]) => name === 'terminate'); assert.equal(prepared[1].workspaceSessionId, id); assert.equal(prepared[2].timeoutMs, 30000); assert.equal(launched[1].profile.workspaceSessionId, id); assert.equal(launched[1].profile.profileId, 'owned-profile'); assert.equal(launched[2].timeoutMs, 15000); assert.equal(terminated[1].sessionId, 'owned-runtime'); assert.equal(terminated[2].timeoutMs, 10000); }));
const deferred = () => { let resolve; const promise = new Promise(done => { resolve = done; }); return { promise, resolve }; };
const directPorts = h => { const { handle: _handle, ...ports } = h.deps; return { ...ports, resolveWorkspaceStoragePaths: () => ({ root: join(h.root, 'store'), backupBaseDir: join(h.root, 'backup'), recoveryDir: join(h.root, 'recovery'), stagingRoot: join(h.root, 'staging'), isCompanion: false }), clearRememberedBase: () => { } }; };
test('remount absent workspace refuses before consuming the window base credential', () => harness(async (h) => { h.state.dialogPath = h.base; const base = await h.invoke('workspace.openBaseDialog', 1); await assert.rejects(h.invoke('workspace.remountBase', 1, base.selectionId), /请先打开工作区/); h.state.dialogPath = h.overlay; const overlay = await h.invoke('workspace.openDialog', 1); const out = await h.invoke('workspace.scan', 1, { overlaySelectionId: overlay.selectionId, baseSelectionId: base.selectionId }); assert.equal(out.session.baseLabel, 'base'); }));
test('transport cache reset revokes selections and service readiness starter together', () => harness(async (h) => { const selection = await h.invoke('workspace.openDialog', 1); h.module.clearWorkspaceIpcCaches(); await assert.rejects(h.invoke('workspace.scan', 1, { overlaySelectionId: selection.selectionId }), /目录选择凭据/); assert.deepEqual(h.calls, []); await h.module.waitForWorkspaceIndexing(); assert.deepEqual(h.calls, []); }));
test('application port capture stays immutable while database close yields', () => harness(async (h) => { const close = deferred(), ports = directPorts(h); ports.clearActiveOperationLog = async () => { h.calls.push(['closeDatabase']); await close.promise; }; const service = h.module.createWorkspaceService(ports); let settled = false; const pending = service.scan({ overlaySelectionId: 'admitted', clearBase: true }, () => Object.freeze({ absolutePath: h.overlay, label: 'owned', kind: 'overlay' }), () => undefined, () => { throw new Error('Unexpected auto base'); }).then(out => { settled = true; return out; }); await Promise.resolve(); assert.equal(settled, false); assert.deepEqual(h.calls, [['closeDatabase']]); ports.releaseEditorCaches = () => { throw new Error('REPLACED_HOST_PORT'); }; ports.resolveWorkspaceStoragePaths = () => { throw new Error('REPLACED_STORAGE_PORT'); }; close.resolve(); const out = await pending; assert.equal(out.workspaceLabel, 'owned'); assert.equal(h.calls[1][0], 'releaseViews'); }));
test('direct runtime service keeps lazy gateway reuse, fresh detect and frozen host ports', () => harness(async (h) => { let gateways = 0; const session = { layers: { overlayRoot: h.overlay }, meta: { workspaceId: 'owned' } }; const ports = { getWorkspaceSession: () => session, getWorkspaceSessionId: () => 'owned-session', localApplicationDataRoot: () => h.root, createGateway: root => { assert.equal(root, h.root); return { owned: ++gateways }; } }; const service = h.module.createWorkspaceRuntimeService(ports); assert.equal(gateways, 0); ports.createGateway = () => { throw new Error('REPLACED_GATEWAY'); }; await service.prepareMe3Profile(); await service.launchMe3('owned-profile'); await service.terminateMe3('owned-runtime'); assert.equal(gateways, 1); await service.detectMe3(); await service.detectMe3(); assert.equal(gateways, 3); assert.equal(h.calls.find(([name]) => name === 'prepareProfile')[1].workspaceSessionId, 'owned-session'); }));
test('another service factory cannot replace a pending scan storage capability', () => harness(async h => { const close = deferred(), ports = directPorts(h); ports.clearActiveOperationLog = async () => { await close.promise; }; const service = h.module.createWorkspaceService(ports); const pending = service.scan({ overlaySelectionId: 'admitted', clearBase: true }, () => Object.freeze({ absolutePath: h.overlay, label: 'owned-a', kind: 'overlay' }), () => undefined, () => { throw new Error('Unexpected auto base'); }); await Promise.resolve(); h.module.createWorkspaceService({ ...directPorts(h), resolveWorkspaceStoragePaths: () => { throw new Error('OTHER_FACTORY_STORAGE_PORT'); } }); close.resolve(); const out = await pending; assert.equal(out.workspaceLabel, 'owned-a'); }));

test('constructing B cannot replace A embedding callback across actual durable publication',()=>harness(async h=>{const a=[],b=[],ports=directPorts(h);ports.scheduleRagEmbedding=(corpus,store)=>a.push([corpus,store]);const service=h.module.createWorkspaceService(ports);await service.scan({overlaySelectionId:'admitted',clearBase:true},()=>Object.freeze({absolutePath:h.overlay,label:'owned-a',kind:'overlay'}),()=>undefined,()=>{throw new Error('Unexpected auto base');});const durable=deferred(),corpus={workspaceId:h.module.getWorkspaceActiveIndex().workspaceId,chunks:[],references:[],stats:{},availability:'unavailable',diagnostics:[]};let entered=false;const store={mergeRagChunkDelta:async()=>null,replaceReferences:async()=>{entered=true;await durable.promise;}};const publishing=h.module.__testPersistActiveRag(store,corpus);assert.equal(entered,true);h.module.createWorkspaceService({...directPorts(h),scheduleRagEmbedding:(corpus,store)=>b.push([corpus,store])});durable.resolve();await publishing;assert.deepEqual(a,[[corpus,store]]);assert.deepEqual(b,[]);assert.equal(h.module.getWorkspaceRag(),corpus);}));
test('constructing B cannot replace activated A readiness analysis starter',()=>harness(async h=>{let a=0,b=0;const ports=directPorts(h);ports.ensureActiveOperationLog=async()=>{a++;throw new Error('OWNED_A_DATABASE');};const service=h.module.createWorkspaceService(ports);await service.scan({overlaySelectionId:'admitted',clearBase:true},()=>Object.freeze({absolutePath:h.overlay,label:'owned-a',kind:'overlay'}),()=>undefined,()=>{throw new Error('Unexpected auto base');});h.module.createWorkspaceService({...directPorts(h),ensureActiveOperationLog:async()=>{b++;throw new Error('OWNED_B_DATABASE');}});await h.module.waitForWorkspaceIndexing();assert.equal(a,2,'A owns both background scan and readiness analysis');assert.equal(b,0,'mere B construction cannot run A readiness through B ports');}));
test('remount activation deliberately binds its service readiness capability',()=>harness(async h=>{let a=0,b=0;const ports=directPorts(h);ports.ensureActiveOperationLog=async()=>{a++;throw new Error('OWNED_A_DATABASE');};const service=h.module.createWorkspaceService(ports);await service.scan({overlaySelectionId:'admitted',clearBase:true},()=>Object.freeze({absolutePath:h.overlay,label:'owned-a',kind:'overlay'}),()=>undefined,()=>{throw new Error('Unexpected auto base');});const next=h.module.createWorkspaceService({...directPorts(h),ensureActiveOperationLog:async()=>{b++;throw new Error('OWNED_B_DATABASE');}});const before=h.module.getActiveWorkspaceSessionGenerationState(),index=h.module.getWorkspaceActiveIndex();await next.remountBase(()=>undefined);assert.ok(h.module.getActiveWorkspaceSessionGenerationState()>before);h.module.applyWorkspaceIndexSnapshot(index);await h.module.waitForWorkspaceIndexing();assert.equal(a,1);assert.equal(b,1,'actual B remount owns the new activation readiness');}));
test('constructing a service after active reset cannot resurrect analysis startup',()=>harness(async h=>{const service=h.module.createWorkspaceService(directPorts(h));await service.scan({overlaySelectionId:'admitted',clearBase:true},()=>Object.freeze({absolutePath:h.overlay,label:'owned-a',kind:'overlay'}),()=>undefined,()=>{throw new Error('Unexpected auto base');});h.module.clearWorkspaceIpcCaches();let b=0;h.module.createWorkspaceService({...directPorts(h),ensureActiveOperationLog:async()=>{b++;throw new Error('OWNED_B_DATABASE');}});await h.module.waitForWorkspaceIndexing();assert.equal(b,0,'cache reset leaves no readiness starter until another activation');}));
